redhat-performance/tuned

tuned/plugins/plugin_selinux.py

plugin_selinux: Import exceptions

---

Makefile

Print path to affected files on 'make lint'

---

profiles/cpu-partitioning/tuned.conf
profiles/laptop-ac-powersave/tuned.conf
profiles/powersave/tuned.conf
profiles/realtime-virtual-guest/tuned.conf
profiles/realtime-virtual-host/tuned.conf
profiles/realtime/tuned.conf
profiles/sap-hana-vmware/tuned.conf
profiles/sap-netweaver/tuned.conf
profiles/spindown-disk/tuned.conf
tuned/consts.py
tuned/plugins/base.py
tuned/plugins/instance/instance.py
tuned/plugins/plugin_bootloader.py
tuned/profiles/loader.py
tuned/units/manager.py

Note: see https://github.com/redhat-performance/tuned/pull/25 for previous discussion.

Introduce ${i:PROFILE_DIR} function

---

tuned/daemon/controller.py

Log errors when applying a profile fails and also log explicitly
when we're trying to load the previously applied profile.
Resolves: rhbz#1434360

Log errors when applying a profile fails

---

man/tuned-adm.8
man/tuned-main.conf.5
man/tuned-profiles-compat.7
man/tuned-profiles-oracle.7
man/tuned-profiles-sap-hana.7
man/tuned-profiles.7
man/varnetload.8

spotted by Debian's lintian tool

fix a few spelling errors in the manpages

---

tuned/plugins/plugin_net.py

Resolves: https://github.com/redhat-performance/tuned/issues/2

plugin_net: Implement setting 'pause' and 'ring' parameters

---

tests/hardware/test_device_matcher.py
tests/profiles/test_profile.py
tuned/hardware/device_matcher.py

profile units are OrderedDicts, not lists

---

tuned.spec

change Source in spec file to github

---

tuned/utils/commands.py

cpulist_unpack supports range, it would be good add negation
support via ^ or !, inorder to exclude cpus from the specified
range.
Fixes #49

Add negation support for cpulist_upack function

---

tuned/logs.py

logs: Fix syntax error

---

recommend.conf

Mark a comment in recommend.conf

---

libexec/defirqaffinity.py

defirqaffinity: Handle errors when settig smp_affinity

---

index.html
style.css

Some of these changes are more important (content), others less so (visual style). Feel free to cherry-pick what you personally like.
Changes in the page content:
- expanded remaining abbreviations
- expanded contractions
- fixed a typo
- tagged more expressions as code
Changes in visual style:
- added an external font to match the one in the header image
- changed the color of links to match header colors
- highlighted code tags to be a bit more distinct
- lighter color for headings

Formatting, stylistic, and language improvements

---

Makefile

Introduce a function for installing python scripts and make use of it in the Makefile. It makes it look a lot cleaner.
We talked about using setuptools in tuned for installation, but after working on it for a while a came to the conclusion that it is really, really not a good idea. Basically, distutils/setuptools don't have the functionality we need and so we have to implement it ourselves. And I don't see the point of using setuptools, if we have to implement a lot of the functionality ourselves anyway. Namely, setuptools do not support at least the following:
* renaming files
* creating empty files
* installing desktop files
* installing scripts to arbitrary locations (/usr/sbin, /usr/libexec)
I created an implementation of the first three things here: …

Makefile: refactor

---

tuned/units/manager.py

Catch exceptions not handled elsewhere to make applying, unapplying
and verifying a profile more robust.
Related: rhbz#1571403

Catch unhandled exceptions

---

profiles/powersave/tuned.conf
tuned/plugins/base.py
tuned/plugins/plugin_cpu.py

Fix setting EPB on Linux 4.13+, support specifying alternative EPB values

---

tuned/plugins/base.py
tuned/plugins/plugin_disk.py
tuned/plugins/plugin_mounts.py
tuned/plugins/plugin_net.py
tuned/plugins/plugin_scheduler.py
tuned/plugins/plugin_sysctl.py
tuned/utils/commands.py

*Important*: we might not want to merge the last commit ("scheduler: Do true rollback of processes' affinity") in its current state. Please read the commit message.

Rework and improve the scheduler plugin

---

tuned/consts.py
tuned/plugins/plugin_bootloader.py

Bootloader plugin fixes

---

tuned-gui.py
tuned/gtk/gui_profile_loader.py

Resolves: rhbz#1536835
Fixes #95

tuned-gui: Fix a traceback

---

tuned/admin/admin.py

Print log excerpt when running 'tuned-adm off'

---

tuned.spec

spec: Simplify the Source0 tag

---

tuned/utils/commands.py

commands: Fix chassis type matching

---

tests/utils/test_commands.py
tuned/utils/commands.py

- It is now possible to exclude cpu range by !1-3
- Also edited test for cpulist_unpack method to test this new
feature
- Resolves rhbz#1533908

Add range feature for cpu exclusion

---

com.redhat.tuned.policy
tuned-adm.py
tuned-gui.glade
tuned-gui.py
tuned/admin/admin.py
tuned/admin/dbus_controller.py
tuned/consts.py
tuned/daemon/controller.py
tuned/daemon/daemon.py
tuned/gtk/gui_plugin_loader.py
tuned/gtk/gui_profile_deleter.py
tuned/gtk/gui_profile_loader.py
tuned/gtk/gui_profile_saver.py
tuned/gtk/tuned_dialog.py
tuned/plugins/base.py
tuned/plugins/plugin_audio.py
tuned/units/manager.py
tuned/utils/commands.py
tuned/utils/plugin_loader.py
tuned/utils/profile_recommender.py

Hi,
this pullrequest:
- simplyfies tuned-gui code
- adds support for config options hints
- fixes running under normal user without using xserver

Add support for config options hints and fix running under normal user

---

tuned/plugins/base.py
tuned/plugins/plugin_bootloader.py
tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_modules.py
tuned/plugins/plugin_scheduler.py
tuned/plugins/plugin_script.py
tuned/plugins/plugin_sysctl.py
tuned/plugins/plugin_sysfs.py
tuned/plugins/plugin_systemd.py

Reverts redhat-performance/tuned#140
Reverting upon discussion with Ondra

Revert "Make copy of instance's devices before executing changes to system"

---

tuned/daemon/controller.py
tuned/daemon/daemon.py

tuned will now on reload of daemon read again configuration
files
Resolves: rhbz#1631744

Reload profile configuration on SIGHUP

---

tuned/plugins/plugin_cpu.py

This avoids wrong warning about a missing intel tool (x86_energy_perf_bias)
Remember arch and x86 CPU vendor to allow arch/vendor specific CPU tunings
in the future

Differ archs and x86 CPU vendors in plugin_cpu

---

tuned-gui.glade

- Fix typos for tuned daemon not running prompt

Fix typo in tuned-gui

---

profiles/balanced/tuned.conf
profiles/powersave/tuned.conf
tuned/plugins/plugin_cpu.py

Fallback to the 'powersave' CPU scaling governor in the 'balanced' and 'powersave' profiles

---

tests/plugins/test_base.py
tuned/daemon/application.py
tuned/hardware/inventory.py
tuned/monitors/base.py
tuned/plugins/base.py
tuned/plugins/hotplug.py
tuned/plugins/instance/instance.py
tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_disk.py
tuned/plugins/plugin_modules.py
tuned/plugins/plugin_net.py
tuned/plugins/plugin_script.py
tuned/plugins/plugin_scsi_host.py
tuned/plugins/plugin_sysctl.py
tuned/plugins/plugin_sysfs.py
tuned/units/manager.py

Fix hotplug-related races and other issues

---

man/tuned-adm.8
tuned-adm.py
tuned/admin/admin.py
tuned/gtk/gui_profile_loader.py
tuned/plugins/plugin_audio.py

Hi,
In pullrequest 138 i overlooked some issues and this pullrequest is meant to fix them.
Please pay attention to code which replaced list profiles and plugins subcommands in tuned-adm. I would like to know your opinion on this. Maybe its little bit hacky but this way we can achieve the same behaviour like with subcommands in python3.

Fix issues from pullrequest 138

---

man/tuned-gui.8

Hi,
here is new manpage for Tuned-gui. If you dont like something please feel free to propose any change.

Add Tuned-gui manpage

---

doc/manual/modules/performance/ref_available-tuned-plug-ins.adoc

This PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=1671107

[Docs] Improved the description of the script plug-in

---

doc/manual/modules/performance/ref_tuned-profiles-distributed-with-red-hat-enterprise-linux.adoc

Resolves [RHBZ#1671105](https://bugzilla.redhat.com/show_bug.cgi?id=1671105).

[Docs] Clarify the information on real-time profiles on RHEL

---

tests-beakerlib/Program-tuned-tried-to-access-dev-mem-between/Makefile
tests-beakerlib/Program-tuned-tried-to-access-dev-mem-between/PURPOSE
tests-beakerlib/Program-tuned-tried-to-access-dev-mem-between/runtest.sh
tests-beakerlib/Tuned-takes-too-long-to-reload-start-when-ulimit/Makefile
tests-beakerlib/Tuned-takes-too-long-to-reload-start-when-ulimit/PURPOSE
tests-beakerlib/Tuned-takes-too-long-to-reload-start-when-ulimit/runtest.sh
tests-beakerlib/bz1416712-Tuned-logs-error-message-if/Makefile
tests-beakerlib/bz1416712-Tuned-logs-error-message-if/PURPOSE
tests-beakerlib/bz1416712-Tuned-logs-error-message-if/runtest.sh
tests-beakerlib/tuned-adm-functionality/Makefile
tests-beakerlib/tuned-adm-functionality/PURPOSE
tests-beakerlib/tuned-adm-functionality/runtest.sh

Upstream first.
Signed-off-by: Robin Hack <rhack@redhat.com>

tests-beakerlib: Add first tests.

---

tuned.spec

Also shipped 'tests' in sources.

spec: added %check to run unit tests

---

tuned/plugins/plugin_scheduler.py

Changing the SMP affinity of some IRQs is not supported. The semantics of ignore_missing is that unsupported tunings are not treated as errors during verification. IRQ SMP affinity being unchangeable can be regarded as an unsupported tuning, so skip verification of these IRQs when ignore_missing is set.
The code assumes that the IRQ numbers point to the same device/event throughout the Tuned run time. We might need to break this assumption in the future (or maybe not; I haven't looked into how IRQ numbers are allocated). Either way, the assumption is already present in the code - rollback assumes the same thing.
Resolves: rhbz#1729936

scheduler: Make IRQ SMP affinity verification respect ignore_missing

---

tuned/profiles/unit.py

unit: accept "True" for replace and enabled options

---

tests/unit/Dockerfile
tests/unit/exports/__init__.py
tests/unit/exports/test_controller.py
tests/unit/globals.py
tests/unit/hardware/__init__.py
tests/unit/hardware/test_inventory.py
tests/unit/monitors/__init__.py
tests/unit/monitors/test_base.py
tests/unit/plugins/__init__.py
tests/unit/plugins/test_base.py
tests/unit/profiles/__init__.py
tests/unit/profiles/test_loader.py
tests/unit/storage/__init__.py
tests/unit/storage/test_factory.py
tests/unit/storage/test_storage.py
tests/unit/utils/__init__.py
tests/unit/utils/test_commands.py
tests/unit/utils/test_global_config.py
tuned.spec

Also replace dependency in specfile and alter dockerfile.
Mock code in globals.py has been removed because it appears that when i first wrote it i misunderstood its effects.

Replace python flexmock module with builtin mock

---

tuned/plugins/plugin_cpu.py

This allows writing e.g.:
[cpu]
force_latency=cstate.name:XYZ|None
In this case if C-state with name XYZ doesn't exist force_latency
will be evaluated to 'None' and nothing will be set and no
error will be reported. If '|None' is omitted, error will be
reported.
Another example:
[cpu]
force_latency=None
Here, it will also set nothing and no error will be reported.
When 'None' is encountered it stops parsing the latency, so writing
'None|1' will also result in no latency set. Both 'none' and 'None' can
be used interchangeably with the same effect.

latency: support None value

---

profiles/realtime-virtual-host/script.sh
tuned.spec

realtime-virtual-host: added ncat requirement

---

man/tuned-profiles.7
profiles/accelerator-performance/tuned.conf

Add accelerator-performance profile

---

profiles/functions

For context: https://github.com/openshift/cluster-node-tuning-operator/pull/111

Try-restart irqbalance service upon writing /etc/sysconfig/irqbalance

---

Makefile

see bug report at
https://github.com/redhat-performance/tuned/issues/246
https://bugs.gentoo.org/706164
Signed-off-by: Yixun Lan <dlan@gentoo.org>

drop bashism syntax, make it happy with dash

---

profiles/network-latency/tuned.conf
tuned/plugins/plugin_bootloader.py

network-latency: used unique cmdline suffix

---

tuned.spec

spectrumcale-ece: package the profile to own subpackage

---

tuned/hardware/inventory.py
tuned/plugins/plugin_cpu.py

Fixed crash when running inside container

---

tuned/utils/profile_recommender.py

recommend: fixed indentation

---

Makefile
tests/unit/exports/__init__.py
tests/unit/exports/test_controller.py
tests/unit/hardware/__init__.py
tests/unit/hardware/test_inventory.py
tests/unit/monitors/__init__.py
tests/unit/plugins/__init__.py
tests/unit/profiles/__init__.py
tests/unit/storage/__init__.py
tests/unit/storage/test_factory.py
tests/unit/storage/test_storage.py
tests/unit/utils/__init__.py
tuned.spec

Fixed building on RHEL-7/CentOS 7

---

profiles/spectrumscale-ece/tuned.conf

Signed-off-by: Luis Bolinches <luis.bolinches@fi.ibm.com>

Update Spectrum Scale ECE profile

---

doc/manual/modules/performance/ref_tuned-profiles-distributed-with-rhel.adoc
man/tuned-adm.8
man/tuned-profiles-atomic.7
man/tuned-profiles-mssql.7
man/tuned-profiles-nfv-guest.7
man/tuned-profiles-oracle.7
man/tuned-profiles-postgresql.7
man/tuned-profiles-realtime.7
man/tuned-profiles-sap-hana.7
man/tuned-profiles-sap.7
man/tuned-profiles-spectrumscale-ece.7
man/tuned-profiles.7
profiles/postgresql/tuned.conf
tuned.spec

A new tuned profile for PostgreSQL database server loads.
Signed-off-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>

added postgresql server profile

---

profiles/cpu-partitioning/tuned.conf

- https://github.com/redhat-performance/tuned/issues/297

Added contrail vrouter dpdk into ps_blacklist

---

experiments/powertop2tuned.py

powertop2tuned: work with PowerTOP 2.13 and newer

---

tuned.spec

syspurpose is provides by subscription-manager on RHEL-9

---

profiles/cpu-partitioning/00-tuned-pre-udev.sh
profiles/cpu-partitioning/tuned.conf
profiles/realtime/tuned.conf

cpu-partitioning,realtime: set cpumasks of all workqueues

---

tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/runtest.sh

tests: added rlRun python detect description to beaker test

---

profiles/mssql/tuned.conf

mssql: update profile to be in sync with MS recommendations

---

tuned/daemon/daemon.py

Fixes: #326
After error while switching profiles attribute _active_profiles is not changed back. That causes issues with wrong signals (and also more issues with restart after etc)

Wrong signal while switch to nonexisting profile

---

tuned.spec
tuned/exports/dbus_exporter.py

Removing depedency on python-decorator package.

---

tuned/plugins/plugin_scheduler.py

This option allows skipping processes belonging to the blacklisted
cgroups. It matches the regular expression against items from the
/proc/PID/cgroups. Items/lines from the /proc/PID/cgroups are separated
by commas ','. Each item consists of the:
hierarchy-ID:controller-list:cgroup-path
Example of the content on which the regular expression is run:
10:hugetlb:/,9:perf_event:/,8:blkio:/
For cgroups v2 the hierarchy-ID is 0 and the controller-list is ''.
For details see man cgroups.7. The only difference from the man
cgroups.7 is that it uses commas for separation of the items instead
of the new lines.
Multiple regular expressions can be separated by the semicolon ';'.
Examples:
[scheduler]
isolated_cores=1
cgroup_ps_blacklist=\b/daemons\b
It will move all processes away from the core 1 …

scheduler: new option cgroup_ps_blacklist

---

man/tuned-adm.8
man/tuned-profiles-atomic.7
man/tuned-profiles-mssql.7
man/tuned-profiles-nfv-guest.7
man/tuned-profiles-nfv-host.7
man/tuned-profiles-openshift.7
man/tuned-profiles-oracle.7
man/tuned-profiles-postgresql.7
man/tuned-profiles-realtime.7
man/tuned-profiles-sap-hana.7
man/tuned-profiles-spectrumscale-ece.7
man/tuned-profiles.7
profiles/openshift-control-plane/tuned.conf
profiles/openshift-node/tuned.conf
profiles/openshift/tuned.conf
tuned.spec

Add OpenShift profiles.

---

recommend.conf
tests/unit/profiles/test_loader.py
tests/unit/profiles/test_locator.py
tests/unit/profiles/test_variables.py
tests/unit/utils/test_global_config.py
tuned-gui.py
tuned.spec
tuned/consts.py
tuned/gtk/gui_plugin_loader.py
tuned/gtk/gui_profile_loader.py
tuned/gtk/gui_profile_saver.py
tuned/profiles/loader.py
tuned/profiles/locator.py
tuned/profiles/variables.py
tuned/utils/global_config.py
tuned/utils/profile_recommender.py

Removing dependency on python-configobj.

---

tuned/profiles/loader.py

Fix improper parsing of include directive

---

tests/beakerlib/variables-support-in-profiles/main.fmf
tests/beakerlib/variables-support-in-profiles/runtest.sh

Add another test which seems suitable to upstream.

beakerlibtests: add new test

---

tuned.spec
tuned/plugins/plugin_net.py

Adding option "txqueuelen" to net_plugin

---

tuned/daemon/daemon.py

daemon: don't do full rollback on systemd failure

---

profiles/latency-performance/tuned.conf
profiles/sap-hana/tuned.conf
profiles/virtual-host/tuned.conf

Related: rhbz#2034069
Related: rhbz#2002744

profiles: use cstate.id_no_zero instead of the cstate.id

---

.packit.yaml

ci: added epel-7 target (for python-2.7)

---

README

Also updated instructions to use dnf instead of the yum.
Related: #396

readme: mention conflicting cpupower and power-profiles-daemon

---

tuned.spec

spec: drop obsoleted defattr and use autosetup macro

---

tuned.spec

Use autosetup macro and drop obsoleted defattr.

Updated spec file

---

tuned/gtk/gui_profile_loader.py

Fixing save call and comments in tuned gui

---

tuned.service

Added more conflicting implementations to the systemd unit file.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2053919.
Closes #394.

Added more conflicting implementations

---

tests/beakerlib/variables-support-in-profiles/runtest.sh

beakerlib: fix systemd rate limiting for variables-support-in-profiles

---

tuned/plugins/plugin_net.py

Adding mtu command to net plugin

---

tuned/plugins/plugin_disk.py

Fixing arguments in disk plugin method

---

tests/unit/utils/test_commands.py
tuned/utils/commands.py

Striping quotes when unpacking cpu list

---

tuned.spec

spec: dropped weak deps where not needed

---

man/tuned.8
tuned-adm.bash

fix a few spelling errors in the manpage
Signed-off-by: lilinjie <lilinjie@uniontech.com>

fix a few spelling errors in the manpage

---

tuned/plugins/plugin_scheduler.py

Signed-off-by: lilinjie <lilinjie@uniontech.com>

fix spelling error

---

profiles/aws/tuned.conf

Resolves: rhbz#1935848
Signed-off-by: Xiao Liang <xiliang@redhat.com>

profiles: added aws profile for aws ec2 instances

---

tuned/gtk/gui_profile_loader.py

Fix tuned/gtk/gui_profile_loader.py spell error.

fix tuned/gtk/gui_profile_loader.py spell error

---

tuned-gui.py
tuned/gtk/gui_profile_loader.py
tuned/utils/polkit.py

Fix spell error

---

tuned/exports/dbus_exporter.py

D-Bus: only send tracebacks through the D-Bus if in the debug mode

---

Makefile

Makefile: added fix for python-3.12

---

tuned/plugins/plugin_sysctl.py

When the `reapply_sysctl` option in `tuned-main.conf` is set to 1, "system" sysctls from `/run/sysctl.d/*.conf`, `/etc/sysctl.d/*.conf` and `/etc/sysctl.conf` will be set *after* TuneD sysctl settings are applied. As `reapply_sysctl=1` is TuneD default, this can be confusing to TuneD users who only rely on TuneD profile settings and do not know about this functionality.  We also need a way to inform other components using TuneD about this.
This PR adds information about reapplied sysctls in TuneD logs.

Inform users about reapplied sysctls

---

tuned/consts.py
tuned/plugins/plugin_cpu.py

Adding support for cpu intel_pstate scaling driver

---

tuned/utils/config_parser.py

build: fixed FTBFS with python2

---

tuned-gui.py

Signed-off-by: lilinjie <lilinjie@uniontech.com>
fix 'is_active' does not work

fix 'is_active' does not work

---

tuned/daemon/application.py
tuned/exports/dbus_exporter.py
tuned/utils/global_config.py

fix log error

---

tuned.spec

spec: dropped unneeded ncat dependency

---

tuned/plugins/plugin_cpu.py

Better log on unsupported hw for pm_qos_resume_latency_us option

---

doc/manual/modules/performance/proc_creating-new-tuned-profiles.adoc
doc/manual/modules/performance/proc_installing-and-enabling-tuned.adoc
doc/manual/modules/performance/proc_modifying-existing-tuned-profiles.adoc
doc/manual/modules/performance/proc_setting-a-tuned-profile.adoc
tuned/admin/admin.py
tuned/daemon/daemon.py

Fix tuned-profiles-adoc error!

fix-tuned-profiles-adoc-error

---

man/tuned-profiles-sap-hana.7

fixed sap-hana docu regarding processor power settings

---

man/tuned-profiles-sap-hana.7
profiles/sap-hana-kvm-guest/tuned.conf
tuned.spec

- Corresponding BZ https://bugzilla.redhat.com/show_bug.cgi?id=2173740
- Updated man page
- Updated spec file

    Added sap-hana-kvm-guest profile

---

profiles/cpu-partitioning/tuned.conf
profiles/network-latency/tuned.conf
profiles/realtime-virtual-guest/tuned.conf
profiles/realtime-virtual-host/tuned.conf
profiles/realtime/tuned.conf

Set of cleanups and fixes for the realtime and cpu-partitioning profiles.
Please see individual patches for details.

Realtime cleanups

---

tuned/consts.py
tuned/daemon/daemon.py
tuned/plugins/base.py
tuned/plugins/instance/instance.py
tuned/plugins/plugin_bootloader.py
tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_modules.py
tuned/plugins/plugin_scheduler.py
tuned/plugins/plugin_script.py
tuned/plugins/plugin_service.py
tuned/plugins/plugin_sysctl.py
tuned/plugins/plugin_sysfs.py
tuned/plugins/plugin_systemd.py
tuned/units/manager.py

This is a follow-up cleanup PR as discussed in https://github.com/redhat-performance/tuned/pull/533.
/cc @yarda

Rename rollback-related constants and variables

---

tuned/daemon/application.py
tuned/daemon/controller.py
tuned/daemon/daemon.py

Serialize SIGHUP processing

---

tuned/daemon/controller.py

api: fixed stop method not to require any parameter

---

tuned/plugins/plugin_cpu.py

Since intel_pstate and amd-pstate use the same per-CPU interface for setting EPP hints, the current cpu plugin supports amd-pstate out of the box.
This commit modifies current P-state related logs and variable names to be explicit about the support for amd-pstate.
Note that while intel_pstate supports global attributes such as `max_perf_pct`, amd-pstate does not.

Be explicit about amd-pstate support

---

tuned-gui.glade

Fix TextView to expand with window

---

tuned/plugins/plugin_cpu.py

The `force_latency` option already supports using C-state IDs/names. This commit extends the support to the `pm_qos_resume_latency_us` option, together with the ability to set fallback values (including the special "n/a" value which disables all C-states).
Resolves: RHEL-21129

plugin_cpu: Support cstate settings of pm_qos_resume_latency_us

---

tuned/plugins/plugin_scheduler.py

This adds the [scheduler] plugin option `irq_process`, which controls whether the plugin performs any tuning of IRQ affinities.
Commit taken from #580 to be merged independently.
Resolves: RHEL-21923

scheduler: add option for ignoring IRQs affinity

---

tuned/plugins/base.py
tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_disk.py
tuned/plugins/plugin_eeepc_she.py
tuned/plugins/plugin_net.py

plugin_net: do not read monitors if dynamic tuning is disabled

---

profiles/sap-netweaver/tuned.conf

sap-netweaver: increased vm.max_map_count

---

profiles/balanced-battery/tuned.conf

This is dependent upon these two merge requests:
https://github.com/redhat-performance/tuned/pull/616
https://github.com/redhat-performance/tuned/pull/601

Update panel power savings for battery-balanced profile

---

functions
tuned/plugins/plugin_irqbalance.py

* Use `IRQBALANCE_BANNED_CPULIST` instead of the deprecated `IRQBALANCE_BANNED_CPUS`
* Remove some dead irqbalance-related code along the way

Update irqbalance configuration

---

profiles/sap-hana/tuned.conf

sap-hana: Set transparent_hugepages to madvise

---

tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_disk.py
tuned/plugins/plugin_scheduler.py
tuned/plugins/plugin_video.py
tuned/plugins/plugin_vm.py

These were all forgotten in 6def0e4.
Resolves: #742

plugins: Add missing instance parameters

---

profiles/realtime/tuned.conf

realtime: Disable appropriate P-State drivers

---

tuned/hardware/device_matcher_udev.py

udev: fix possible traceback in device matcher
