tuned/plugins/plugin_disk.py

Provide the correct number of parameters to the '_set_readahead' method.
This fixes a traceback when setting the 'readahead_multiply' option.
I assume the 'sim' parameter to '_set_readahead' means 'simulated' (it
is handled in that sense), so we should set the value to False, because
we are actually enabling/disabling the tunning here.

plugin_disk: Fix setting 'readahead_multiply'

---

tuned/plugins/plugin_disk.py

plugin_disk: Mark _device_is_supported as a classmethod

---

tuned/plugins/plugin_scsi_host.py

plugin_scsi_host: Mark _device_is_supported as a classmethod

---

tuned/admin/admin.py

This also makes a pylint error message go away.

Remove an unreachable return statement

---

tuned-gui.py
tuned/exports/interfaces.py

NotImplemented is not an exception type. This patch makes some pylint
errors go away.

Raise NotImplementedError instead of NotImplemented

---

Makefile

The target executes pylint on all *.py files, except for those in the ./tests and ./experiments subdirectories. The tests subdirectory is out-dated (lots and lots of errors) and the experiments subdirectory doesn't seem like a place you'd want to check everytime you make a change. What do you think?

Add 'lint' target to Makefile

---

tuned/logs.py

Previously if you ran 'tuned -l log', it would crash with:
OSError: [Errno 2] No such file or directory: ''
This patch fixes the bug.

Fix logging to file in the current directory

---

tuned-main.conf
tuned/consts.py
tuned/daemon/application.py
tuned/plugins/base.py
tuned/plugins/instance/instance.py
tuned/units/manager.py

Resolves: rhbz#1246172
Allow specifying order in which individual plugin instances are to be
executed.
Each instance can be given the 'instance_priority' option
in the profile configuration. The value must be an integer (it can be
negative). If no priority is specified, it is inherited from the parent
profile, or set to the default instance priority, if no parent profile
specifies the priority for that instance.
The default instance priority is by default zero, but it can be set to
a different value using the 'default_instance_priority' option in the
global configuration file.
Creating plugin instances, assigning devices to instances, initializing
instances, applying, updating and verifying tuning are all done in order
from lowest numerical instance priority to highest. Unapplying tuning …

Implement instance priority

---

tuned/plugins/hotplug.py

Resolves: rhbz#1246172
This fixes commit 363d74815a.

Assign hotplugged devices in priority order too

---

tuned/plugins/base.py
tuned/plugins/hotplug.py
tuned/plugins/plugin_audio.py
tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_disk.py
tuned/plugins/plugin_mounts.py
tuned/plugins/plugin_net.py
tuned/plugins/plugin_scsi_host.py
tuned/plugins/plugin_usb.py
tuned/plugins/plugin_video.py

The _device attribute should always be the same as the union of
_assigned_devices and _free_devices, therefore it's redundant.
Its existence in my opinion brings only confusion and a potential
source of inconsistencies.

Remove the '_devices' attribute in plugins

---

tuned/daemon/application.py
tuned/gtk/gui_plugin_loader.py
tuned/hardware/__init__.py
tuned/hardware/device_matcher_udev.py
tuned/hardware/inventory.py
tuned/plugins/base.py
tuned/plugins/instance/instance.py
tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_disk.py
tuned/plugins/plugin_net.py
tuned/plugins/plugin_scsi_host.py
tuned/plugins/plugin_usb.py
tuned/plugins/plugin_video.py
tuned/plugins/repository.py
tuned/profiles/merger.py
tuned/profiles/unit.py
tuned/units/manager.py

A new option 'devices_udev_regex' can be used in profile
configuration to specify devices to which a plugin instance
should be applied.
The option can contain a python regular expression, as specified
in https://docs.python.org/2/library/re.html#regular-expression-syntax.
The expression is effectively matched against the output of
udevadm info --query=property -n <device_path>
If the option 'devices_udev_regex' is specified, the 'devices' option
is ignored. If it is not specified, then the matching is done the same
way as previously, i.e. against 'devices'.

Implement udev-based device matching

---

tuned/units/manager.py

The plugins were not getting cleaned up properly, so e.g. after
a profile switch instances of the Plugin class would get piled up.
This fixes commit 363d74815a.

Fix plugin cleanup

---

tuned/plugins/hotplug.py

Resolves: rhbz#1251240
This fixes commit f14ae65bd2.

Assign hotplugged devices based on udev matching too

---

tuned/plugins/base.py

Clean up device and non-device commands it reversed order, compared to
the order in which they were applied. It makes more sense that way to me.
Related: rhbz#1246176

Perform command cleanup in reversed order

---

com.redhat.tuned.policy

The policy for running the 'verify_profile_ignore_missing' D-Bus method
was missing, so only root could run it. This commit adds the policy, so
that it is the same as the policy for regular 'verify_profile'.

Allow running verify_profile_ignore_missing to all users

---

tuned/plugins/plugin_disk.py

Don't run 'hdparm -S' with a lower spindown value than previously
applied, if the drive has already spun down. Executing the command
in that case makes the drive spin up with some HDDs.
Resolves https://github.com/redhat-performance/tuned/issues/1

disk: Don't apply lower spindown value if drive has spun down

---

tuned/plugins/plugin_net.py

Fix an invocation of execute() after its API changed.
Reproducer:
Run tuned with the following profile, and you'll see error messages
'tuned.utils.commands: Executing ethtool error: ethtool: bad command line argument(s)'
in the log. Replace 'enp0s25' with your ethernet interface:
[net]
devices=enp0s25
coalesce=rx-usecs 4

plugin_net: Fix invocation of execute()

---

tuned-gui.desktop

it's deprecated:
https://specifications.freedesktop.org/desktop-entry-spec/1.0/apc.html

drop the encoding keyword from the desktop file

---

man/tuned-adm.8
man/tuned-main.conf.5
man/tuned-profiles-atomic.7
man/tuned-profiles-compat.7
man/tuned-profiles-cpu-partitioning.7
man/tuned-profiles-nfv-guest.7
man/tuned-profiles-nfv-host.7
man/tuned-profiles-oracle.7
man/tuned-profiles-realtime.7
man/tuned-profiles-sap-hana.7
man/tuned-profiles-sap.7
man/tuned-profiles.7
man/tuned.8
man/tuned.conf.5

the macros are called .nf and .fi, not .NF and .FI
Test:
% LC_ALL=en_US.UTF-8 MANROFFSEQ='' MANWIDTH=80  man --warnings \
-E UTF-8 -l -Tutf8 -Z <file> >/dev/null
53: warning: macro `NF' not defined
74: warning: macro `FI' not defined
Spotted by rpmlint and lintian.

fix NF/FI macros in manpages

---

man/tuned-adm.8
tuned-adm.py
tuned/admin/admin.py

List available profiles when 'tuned-adm profile' is run
without a profile name.
Resolves: rhbz#988433

List available profiles on 'tuned-adm profile'

---

Makefile

pkg-config is the most reliable and cross-distro way to get information about the systemd folders on a system.
only rely on RPM macros when pkg-config is not installed or systemd.pc is not available.

try to get unitdir and tmpdir from pkg-config

---

tuned/admin/admin.py

Added note about restarting tuned using 'systemclt' in addition to the existing reference to 'service'.

Updated help outputs

---

tuned-gui.desktop

I want to propose to change the menu entry category from System to Settings;HardwareSettings.
While updating the tuned package for openSUSE, the build checker complained that the used menu category 'System' is not sufficient enough.
After digging into https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories#System
the right category seems to be Settings;HardwareSettings.
To make the appearance of tuned-gui the same for every distribution I thought pushing this upstream would be a good idea!

Change desktop menu category for tuned-gui from System to Settings;HardwareSettings

---

tuned/gtk/gui_plugin_loader.py
tuned/gtk/gui_profile_loader.py
tuned/gtk/managerException.py

Currently the modules in tuned/gtk/* include shebangs. Since these modules are not intended for executing remove them.
This will also silence rpmlint warnings.

Remove unnecessary shebang from gtk python modules.

---

tuned-main.conf
tuned/consts.py
tuned/daemon/application.py
tuned/hardware/inventory.py
tuned/utils/commands.py
tuned/utils/global_config.py

The udev monitor buffer size was increased to 1MB. Also, a new
configuration option 'udev_buffer_size' can be specified in
/etc/tuned/tuned-main.conf to set a different buffer size.
Values such as '204800', '200KB', '200 KB' (with space) or '1 MB'
are recognized. If no unit is specified, the number is taken as
the number of bytes.
Resolves: rhbz#1442306

Increase udev monitor buffer size, make it configurable

---

tuned/plugins/plugin_cpu.py

Don't log error in commands.execute() if MSR_IA32_ENERGY_PERF_BIAS
is not supported. A message with level WARN is already logged
afterwards:
WARNING  tuned.plugins.plugin_cpu: your CPU doesn't support
MSR_IA32_ENERGY_PERF_BIAS, ignoring CPU energy performance bias
Resolves: rhbz#1443182

cpu: Don't log error in execute() if EPB is not supported

---

tuned/plugins/base.py
tuned/plugins/plugin_audio.py
tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_disk.py
tuned/plugins/plugin_net.py
tuned/plugins/plugin_scheduler.py
tuned/plugins/plugin_scsi_host.py
tuned/plugins/plugin_usb.py
tuned/plugins/plugin_video.py
tuned/utils/commands.py

Note: With commit 66d4843 you get tons of warnings in the logs when the isolated_cores parameter is set, such as the following:
tuned.plugins.plugin_scheduler: Affinity of PID 9534 is not changeable.
tuned.plugins.plugin_scheduler: Affinity of PID 522 is not changeable.
It seems all the PIDs it's complaining about are kernel threads. Maybe we could change the behaviour so that:
* Tuned doesn't complain about not being able to change affinity of kernel threads, and/or
* Log only one message after the migration is completed saying that _some_ tasks could not be migrated

Improve logging

---

tuned/plugins/plugin_video.py

Support the 'dpm' power method on Radeon GPUs. Implement automatic selection of the best power method and use it in the balanced profile.
Resolves: rhbz#1417659

[WIP] Video plugin improvements

---

tuned/exports/dbus_exporter.py

Previously if the profile was applied before all methods and
signals were exported on DBus, the daemon thread (_thread_code()
in daemon.py) could crash after attempting to emit a signal on DBus
announcing that a profile was applied.
A regular user is unlikely to run into the race in practice, but it
frequently happens when applying an empty profile for testing purposes.

Fix race between DBus exporter startup and applying a profile

---

profiles/balanced/tuned.conf
profiles/desktop-powersave/tuned.conf
profiles/powersave/tuned.conf
tuned/plugins/plugin_video.py

In the end, I like your version better. It's short and sweet. But let's prefix DPM states with 'dpm-' to prevent future name collisions. Graphics cards manufacturers are very creative, I'm sure they will come up with a completely new power management mechanism soon :).
Also, change the state in powersave profiles to 'battery' - for some strange reason, there's
no such DPM state as 'powersave' and the lowest power consumption state is called 'battery'.

plugin_video: Prefix DPM states with 'dpm-'

---

tuned/profiles/loader.py

Variables in the 'devices' option were not being expanded. This is
bad. It shows that the current variable expansion system is broken.
We need to come up with a consistent, well-defined way of expanding
variables. Preferably it should be done all in one place.
The expansion is probably still not done for options 'type', 'enabled',
'replace', 'devices_udev_regex', 'script_pre' and 'script_post'. Let's
deal with that later, as we don't need it in our profiles right now.
Related: rhbz#1490399

Expand variables in the 'devices' option

---

profiles/realtime-virtual-host/run-tscdeadline-latency.sh
profiles/realtime-virtual-host/script.sh

RHEL ships tscdeadline_latency.flat as part of the qemu-kvm-tools package, but Fedora does not. In addition, the script that runs it refers to /usr/libexec/qemu-kvm that doesn't exist in Fedora (where qemu-kvm is simply on the path).
The solution is to package the benchmark in tuned, and once we do this we can look it in /usr/share/tuned instead of /usr/share/qemu-kvm.
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

port realtime virtual host profile to Fedora

---

index.html

The fixes:
- Closed the <link> element with the correct "/>" XHTML syntax.
- Wrapped the header <img> and the associated <map> element in a simple <div>.
Also, I've indented a couple of lines for the structure to be slightly clearer.

Fixed W3C validation errors; added more indentation

---

tuned/plugins/plugin_scheduler.py

Use PF_KTHREAD to identify kernel threads

---

profiles/cpu-partitioning/script.sh

Consistently use 'balance' instead of 'rebalance' in cpu-partitioning

---

profiles/throughput-performance/tuned.conf

A common source of confusion within tuned is the lack of suffix
on the readahead specification in the throughput-performance
tuned.conf. This confusion is resolved, in general, by comparing
the value, for example, to blockdev or lvdisplay output. Avoid
future end-user confusion by adding a comment to the
throughput-performance tuned.conf file, explaining that the default
is in KiB, and noting the allowance of a sector suffix as well.
Signed-off-by: John Pittman <jpittman@redhat.com>

tuned: Add readahead comment to throughput-performance tuned.conf

---

tuned/plugins/plugin_bootloader.py

Resolves: rhbz#1571403
Fixes #82

bootloader: Check if grub2_cfg_file_name is None in _remove_grub2_tuning()

---

tuned-adm.py

Running tuned-adm without arguments using Python 3 results in
a traceback. This is because in this case parse_args does not
exit with a usage message in Python 3 and the 'action' option
is then undefined. So let's check for this case and print the
usage message ourselves. There may be a better solution to this,
but I wasn't able to come up with anything in a reasonable amount
of time.

tuned-adm: Fix a traceback when run without arguments

---

tuned-adm.py

The previous fix was not sufficient, tuned-adm still tracebacks
in cases when options are specified, but an action is not, e.g.:
$ python3 ./tuned-adm.py -a
Traceback (most recent call last):
File "./tuned-adm.py", line 106, in <module>
action_name = options.pop("action")
KeyError: 'action'
The object returned by ArgumentParser.add_subparsers recognizes
a 'required' attribute (at least in Python 3), which is probably
meant to allow to make specifying an action required, but I wasn't
able to make it work properly, I get errors such as
Traceback (most recent call last):
File "./tuned-adm.py", line 98, in <module>
args = parser.parse_args(sys.argv[1:])
File "/usr/lib64/python3.6/argparse.py", line 1730, in parse_args
args, argv = self.parse_known_args(args, namespace)
File …

tuned-adm: Fix a traceback when run without action specified

---

tuned-gui.py

Previously the sorting was done by comparing the objects themselves,
which is not what we want and it doesn't work in Python 3 - TypeError
is raised, e.g:
TypeError: '<' not supported between instances of 'BootloaderPlugin' and 'MountsPlugin'

tuned-gui: Sort plugins based on their name

---

tuned/daemon/daemon.py

This commit removes misleading info message about rolling back changes when running tuned in one-shot mode.

Show rollback info message only when in daemon mode.

---

tuned.spec
tuned/utils/commands.py

It's only available on x86_64.
Resolves: rhbz#1565598

Make python-dmidecode a weak dependency

---

profiles/virtual-host/tuned.conf

The default tuned profile for an oVirt cluster is "virtual-host".
Recently, testing at customer sites and performance labs has shown
that "latency-performance" yields better results. This patch makes
virtual-host profile identical to latency-performance. This seems
better than uniting them since this way we maintain the possibility
to tweak them in different ways in the future according to further
findings.
fixes #131 
Change-Id: I1a64fac22364b17de1279a3e1f37a6b7eb0fe61b
Bug-Url: https://bugzilla.redhat.com/1588932
Signed-off-by: Ori_Liel <oliel@redhat.com>

Make virtual-host identical to latency-performance

---

profiles/cpu-partitioning/script.sh
profiles/functions
profiles/realtime-virtual-host/script.sh

Disabling the ksm and ksmtuned services during boot seems to cause
problems, so do it only once when the profile is first applied and
reenable the services only when full rollback is required.
Resolves: rhbz#1622239

Disable KSM only once, re-enable it only on full rollback

---

tuned/logs.py

The returned string was only pseudo random. It is only used for the
log_capture_start() mechanism at the moment. Therefore an attacker might
be able to guess the tokens of other users. Since this data it publicly
available anyways it should not be a big issue, however.

logs: actually use SystemRandom source for generating a random string

---

tuned/plugins/plugin_scheduler.py

Make sure the file objects returned by evlist.get_pollfd()
don't go out of scope and get destroyed too soon. This is
a workaround for python3-perf rhbz#1659445.
Resolves: rhbz#1659140

scheduler: Keep polling file objects alive long enough

---

tuned/plugins/base.py
tuned/plugins/plugin_bootloader.py
tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_disk.py
tuned/plugins/plugin_modules.py
tuned/plugins/plugin_scheduler.py
tuned/plugins/plugin_script.py
tuned/plugins/plugin_sysctl.py
tuned/plugins/plugin_sysfs.py
tuned/plugins/plugin_systemd.py

- these changes will protect tuned's execution thread from errors
caused by changes of instance's devices list while execution
thread iterates over them
- fixes problem with bad recognition of disk caused
by use of python3
- Resolve: rhbz#1592743

Make copy of instance's devices before executing changes to system

---

tuned/monitors/base.py
tuned/plugins/plugin_disk.py

when udev sends remove event it does not send any device
attributes with it so _device_is_supported check must be omitted
also when getting devices sys_name ensure it is string object
by using str()
Resolves: rhbz#1595156

fix disk plugin/plugout problem

---

tuned/profiles/unit.py

- 1 is not equal to "1" in python
- Resolves: rhbz#1613379

Fix unit configuration reading

---

tuned-main.conf

100KB is not a lot, it can fill up quickly.

Increase max log file size in the default config file

---

Makefile
tests/plugins/test_base.py

The bug is no longer reproducible with
python3-pylint-2.1.1-2.fc29.noarch.

Makefile: Drop a workaround for a pylint bug and run pylint on tests too

---

profiles/hpc-compute/tuned.conf

Added a profile for common HPC workloads. It sets basic VM policies common to compute nodes and enables a few network settings that optimize for large, contiguous, file operations.

Added profile for HPC compute workloads

---

experiments/kwin-stop/xlib-example.py
tuned/plugins/plugin_systemd.py
tuned/profiles/merger.py

In python, 'is None' should be used instead of '== None' to check if
something is None.

Fix checking for None values

---

tuned/admin/admin.py

Hi,
this pullrequest fixes issue with `tuned-adm recommend` command working in off-daemon mode.
For more information please read commit message.
Resolves: rhbz#1687397

Fix tuned-adm recommend off-daemon mode

---

tuned/utils/profile_recommender.py

Hi,
recently we've noticed mutliple error messages warning user about running virt-what without root privileges. This pull request makes from these multiple messages one which says exactly what is wrong.
Problem occured when executing:
$ tuned-adm recommend

Improve logging of tuned-adm recommend

---

tuned/utils/profile_recommender.py

The effective UID is what matters when it comes to the ability to
perform privileged actions, not the real UID.

Check for root privileges by inspecting the effective UID

---

profiles/virtual-host/tuned.conf

The force_latency parameter belongs to the cpu plugin, so that's the
section it needs to be in.
Fixes #132
Resolves: rhbz#1569375

virtual-host: Fix setting force_latency

---

doc/manual/README.adoc
doc/manual/assemblies/assembly_getting-started-with-tuned.adoc
doc/manual/master.adoc
doc/manual/modules/performance/proc_installing-and-enabling-tuned.adoc
doc/manual/modules/performance/ref_built-in-functions-available-in-tuned-profiles.adoc

As pointed out in [RHBZ#1680386](https://bugzilla.redhat.com/show_bug.cgi?id=1680386), our documentation wasn't completely consistent in how it classified and referred to the components of Tuned.
This PR fixes the inconsistencies and establishes naming conventions as described in the manual's readme: https://github.com/mrksu/tuned/blob/fix-terminology/doc/manual/README.adoc#naming-conventions

[Docs] Tweak the terminology around Tuned and its components

---

com.redhat.tuned.policy

As these interfaces allow loading and thus executing code from plugins
the default permission policy is lowered from:
yes:yes:yes
to
auth_admin:auth_admin:yes
So only users logged into the X server are allowed to use this interface
without extra root/admin authentication.
This was found by security review by Matthias Gerstner
<matthias.gerstner@suse.com>
Also see:
https://github.com/redhat-performance/tuned/issues/180

Lower permissions for plugin info dbus interfaces

---

tuned/plugins/plugin_sysctl.py

sysctl options such as `net.ipv4.tcp_wmem` and `net.ipv4.tcp_rmem` include tabs. When you use `tuned-adm verify`, the changes report back as broken as the whitespaces are different because one side has been sanitized but the other side has not. This pull request will fix that.

Fix verifying sysctl options with tabs

---

tuned/plugins/plugin_sysctl.py

Ignore non-existent sysctl settings from the system configuration files
(/etc/sysctl.conf, etc.). Logging errors about these settings hurts user
experience, if the non-existent settings are in fact real settings that
are just temporarily unavailable. For example, the following settings
(from /usr/lib/sysctl.d/00-system.conf on RHEL-7) are not available until
the br_netfilter module is loaded. However once that module is loaded,
it is often desirable to set these, so having them in a RHEL-provided
configuration file makes sense.
net.bridge.bridge-nf-call-ip6tables = 0
net.bridge.bridge-nf-call-iptables = 0
net.bridge.bridge-nf-call-arptables = 0
This change restores the old behaviour before the recent rewrite of the
sysctl plugin away from using the 'sysctl' program (running
'sysctl …

sysctl: Ignore non-existent settings from system sysctl configs

---

doc/manual/assemblies/assembly_getting-started-with-tuned.adoc
doc/manual/modules/performance/proc_installing-and-enabling-tuned.adoc
doc/manual/modules/performance/ref_tuned-profiles-distributed-with-rhel.adoc

Atomic Host no longer exists in RHEL 8 (replaced by CoreOS), so let's not talk about profiles targeted at it.
Resolves [RHBZ#1680387](https://bugzilla.redhat.com/show_bug.cgi?id=1680387).

Remove references to RHEL Atomic Host from the manual

---

tuned/plugins/plugin_sysctl.py

A bare 'except' statement can catch (and hide) all sorts of errors,
including NameError. Fix it to catch only the errors we really expect.

Fix a bare 'except' statement

---

profiles/cpu-partitioning/script.sh
profiles/functions
profiles/realtime/script.sh
profiles/realtime/tuned.conf
tuned/plugins/plugin_script.py

The two realtime profiles needs to do cpu isolation just like cpu-partitioning profiles.  Do proper configuration for irqbalance service for them just like the cpu-partioning profile otherwise irqbalance might collapse with tuned on configuring system IRQs.

Apply irqbalance service tuning for realtime-virtual-{host|guest} profiles

---

tuned/plugins/plugin_cpu.py

Variables in force_latency, min_perf_pct, max_perf_pct and no_turbo options were not being expanded. Fix it.
Fixes #203

cpu: Expand variables in all commands

---

experiments/kwin-stop/xlib-example.py
experiments/powertop2tuned.py
libexec/defirqaffinity.py
libexec/pmqos-static.py
systemtap/varnetload
tuned-adm.py
tuned-gui.py
tuned.py

This may ease development, because development environment will
be probably already on python3.

Use python3 interpreter by default

---

tests/beakerlib/Program-tuned-tried-to-access-dev-mem-between/runtest.sh
tests/beakerlib/Tuned-takes-too-long-to-reload-start-when-ulimit/runtest.sh
tests/beakerlib/tuned-adm-functionality/runtest.sh

I would recommend to get rid of the old rhts imports as well.

Remove obsolete rhts imports from beakerlib tests

---

tuned/hardware/device_matcher_udev.py

In order to allow matching multiple parameter-value pairs in a single regex, we need to use re.DOTALL, because the parameter-value pairs are on separate lines. Consider the following regex:
^ID_MODEL=SD_MMC$.*^ID_MODEL_ID=0316$
Previously it would not much a string such as the following:
ID_MODEL=SD_MMC
ID_MODEL_ENC=SD\x2fMMC\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_MODEL_ID=0316
Now it does match.
It should be noted that this change is not entirely backwards-compatible. Some user-written regexes can now start to match where they shouldn't. For example the following regex will now match even if 'ID_MODEL_ID' and '0316' are on different lines.
ID_MODEL_ID.*0316
The primary motivation for this change is making the udev matcher behave the same as the cpuinfo matcher that will be written to …

Use re.DOTALL in the udev device matcher

---

tuned/plugins/plugin_cpu.py

Update checking if EPB is supported so that it works with recent versions of the x86_energy_perf_policy tool. Newer versions of x86_energy_perf_policy, unlike older versions, exit with a zero exit code even if the CPU doesn't support EPB. Newer versions of the tool give no ouput on stdout if EPB is not supported, so check for that.
In the future, we might like to determine if EPB is supported by searching /proc/cpuinfo for specific CPU flags. However the solution described in the previous paragraph should work just fine for now.
Resolves: rhbz#1690929

cpu: Update checking if EPB is supported

---

tuned/plugins/plugin_bootloader.py

Previously, if the grub.cfg patching code ran into a grub.cfg file that was empty, all subsequent grub.cfg files would get skipped and would not be patched. This behaviour doesn't make much sense to me. We should skip empty grub.cfg files and patch all the non-empty ones.
Resolves: rhbz#1622646

bootloader: Don't abort patching if grub.cfg is empty

---

tuned/hardware/device_matcher_udev.py

This reverts commit d0b43e8b74aa9c1ae3ab69abf7fb8ece713b7ddf.
This reverts https://github.com/redhat-performance/tuned/pull/216.
The original change is completely unnecessary. The following regex (mentioned in the commit message of the original commit)
^ID_MODEL=SD_MMC$.*^ID_MODEL_ID=0316$
can be simply changed like this
^ID_MODEL=SD_MMC$(.|\n)*^ID_MODEL_ID=0316$
and it'll match the desired string without re.DOTALL
ID_MODEL=SD_MMC
ID_MODEL_ENC=SD\x2fMMC\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_MODEL_ID=0316
So it seems completely unnecessary to introduce this user-visible change in behaviour.
Also, the change would in fact make matching strings on a single line harder, because the following regex
^ID_MODEL=.*SD_MMC$
would also match the following multi-line string with re.DOTALL …

Revert "Use re.DOTALL in the udev device matcher"

---

tuned/plugins/plugin_disk.py

Previously the following invalid setting caused traceback:
[disk]
readahead=abcd

plugin_disk: fixed traceback on invalid readahead values

---

tuned/profiles/functions/function_cpuinfo_check.py
tuned/profiles/loader.py
tuned/profiles/merger.py
tuned/profiles/unit.py
tuned/units/manager.py

Also added cpuinfo_check builtin function.
It's possible to write now:
[variables]
cannonalake_cpuinfo=.*\bGenuineIntel\b.*
cannonlake_uname=x86_64
[cpu_cannonlake]
type=cpu
cpuinfo_regex=${cannonlake_cpuinfo}
uname_regex=${cannonlake_uname}
force_latency=C1
[disk_cannonlake]
type=disk
cpuinfo_regex=${cannonlake_cpuinfo}
uname_regex=${cannonlake_uname}
readahead=4092
...
And the tuning will be applied only on machines which have
'GenuineIntel' string in the /proc/cpuinfo and x86_64 architecture (from
uname). Both 'cpuinfo_regex' and 'uname_regex' are optional - if not
used it has the same effect as if matching regex is used. This example
used variables but it also works without it.
Also cpuinfo_check builtin function was added, so it's possible to write
the following now:
[main] …

plugins: support cpuinfo_regex and uname_regex matching

---

Makefile

Previously, when unit tests were run, python would leave behind files with bytecompiled modules. It's not useful, it just clutters the repository. And it could potentially lead to problems - it seems to have lead to some problem for me earlier today when running git bisect to find out when `make test` started failing.

Make python not write bytecode files when unit tests are run

---

man/tuned-main.conf.5
tuned-main.conf
tuned/plugins/plugin_sysctl.py

The reapply_sysctl functionality was originally added to address rhbz#1302953, which was about Tuned overriding sysctl config files from /etc, which was deemed undesirable. The bug said nothing about sysctl config files from /usr/lib/sysctl.d, /lib/sysctl.d or /usr/local/lib/sysctl.d.
Having sysctl configs from /usr override Tuned profiles causes problems (rhbz#1759597). Also, it seems reasonable for Tuned profiles to override sysctl configs from /usr - a Tuned profile is often explicitly chosen by the user, whereas sysctl configs from /usr are provided by system packages whether the user wants them or not.
Also, in RHEL-6, tuned used to ignore sysctl config files from /usr, as far as I can tell.
Resolves rhbz#1759597

sysctl: Make reapply_sysctl ignore configs from /usr

---

tuned/daemon/controller.py

Please take a look at the second commit. The `return False` when the daemon is not running has been there for ages, however I'm not sure if it serves a specific purpose. Do you think we can drop it?

Fix a hang on SIGHUP when the preset profile does not exist

---

libexec/defirqaffinity.py

The last callers to this realtime profile helper script
had been nuked by this commit:
c2dfc1f80695f0cdd6782a6d72787b378128fc47

Remove defirqaffinity.py

---

tuned/profiles/merger.py
tuned/profiles/unit.py

Consider the following:
profile_1:
[cpu]
force_latency=10
no_turbo=1
[disk]
readahead=4098
If you want to include it in profile_2 and just drop the force_latency
option now you can write:
[main]
include=profile_1
[cpu]
drop=force_latency
Previously, you had to use the replace option and add all other options
which were used in the inherited profiles like:
[main]
include=profile_1
[cpu]
replace=true
no_turbo=1
There can be named multiple options in the drop. As the delimiter comma
',' or semicolon ';' can be used, spaces are ignored, e.g.:
[cpu]
drop=force_latency, no_turbo
Fixes: #227

Added drop option allowing dropping options from inherited plugins

---

man/tuned-profiles-sap-hana.7
profiles/sap-hana/tuned.conf

Made sap-hana profile standalone.
Resolves: rhbz#1779821

sap-hana: updated tuning

---

profiles/latency-performance/tuned.conf

Update sysctl tunings in the latency-performance profile based on feedback from the performance team.
Resolves: rhbz#1779759

latency-performance: Update sysctl tunings

---

man/tuned-profiles.7
profiles/sst/tuned.conf

Intel's new Speed Select Technology (SST) is a process power management
technology introduced by Intel that allows for throughput and per-core
performance configurations and optimizations such as allowing for
prioritization of workloads on specific cores by sacrificing performance
on other cores.
Intel has released several CascadeLake processors, commonly referred to
as CascadeLake-N, with this technology and will introduce further SST
related technologies in the next few years.
These new technologies require the disabling of the intel-pstate driver
configuration in tuned as it may interfere with the user chosen per-core
configurations of SST.
Add a new SST profile to tuned for general use.
Resolves:  https://bugzilla.redhat.com/1743879
Signed-off-by: Prarit Bhargava <prarit@redhat.com> …

Add Intel Speed Select Technology (SST) Profile

---

profiles/oracle/tuned.conf

Turn off NUMA balancing, according to feedback from the performance team.
Resolves: rhbz#1782233

oracle: Turn off NUMA balancing

---

profiles/cpu-partitioning/tuned.conf
profiles/realtime/tuned.conf

Make sure the isolated_cores and no_balance_cores variables are defined before any of the variables that use them are defined. This enforces a certain ordering of variable expansions so that child profiles can set the variables directly in the profile (tuned.conf), e.g.:
[main]
include=cpu-partitioning
[variables]
isolated_cores=3
Resolves: rhbz#1781664

profiles: Make sure variables are defined before use

---

man/tuned-profiles.7
profiles/intel-sst/tuned.conf

Also updated intel-sst profile manual page describing its usage.
Related: rhbz#1743879

profiles: renamed sst profile to intel-sst

---

tuned/profiles/functions/base.py
tuned/profiles/functions/function_assertion.py
tuned/profiles/functions/function_assertion_non_equal.py
tuned/profiles/functions/function_hex2cpulist.py
tuned/profiles/functions/function_kb2s.py
tuned/profiles/functions/function_regex_search_ternary.py
tuned/profiles/functions/function_s2kb.py
tuned/profiles/functions/function_virt_check.py

There can be lower number of arguments than the max limit.
Also fixed definition of functions which wrongly used the API.
I.e. it should work this way:
__init__("FUNC", 3, 3)
__init__("FUNC", 4, 3)
__init__("FUNC", 3)
__init__("FUNC", 0, 3)
__init__("FUNC", 0)

builtin_functions: fixed check for number of arguments

---

tests/unit/exports/test_controller.py
tests/unit/hardware/test_device_matcher.py
tests/unit/hardware/test_device_matcher_udev.py
tests/unit/hardware/test_inventory.py
tests/unit/monitors/test_base.py
tests/unit/plugins/test_base.py
tests/unit/profiles/test_loader.py
tests/unit/profiles/test_locator.py
tests/unit/profiles/test_merger.py
tests/unit/profiles/test_profile.py
tests/unit/profiles/test_unit.py
tests/unit/utils/test_commands.py
tests/unit/utils/test_global_config.py
tuned.spec

Fixes https://github.com/redhat-performance/tuned/issues/241
Fedora is removing the unittest2 package: https://bugzilla.redhat.com/show_bug.cgi?id=1794222
tuned is not targeting Python 2.6: https://github.com/redhat-performance/tuned/issues/241#issuecomment-588320175
One thing not present in Python 2.7 is `assertItemsEqual()` -- renamed to `assertCountEqual()`.
Related, `mock` was also listed as a requirement in the spec file,
but all the imports are from `unittest.mock`, hence removed.

Remove usage of unittest2, use unittest from the standard library

---

tuned/plugins/plugin_bootloader.py

Currently when `grub.cfg` file is not found, the [bootloader] plugin still modifies `/etc/tuned/bootcmdline` file.  However, during rollbacks, the settings applied to that file are not rolled back.  This becomes a problem in (containerized) environments when `grub.cfg` file does not exist.  This patch will make the behaviour more consistent and unapply the settings in `/etc/tuned/bootcmdline` even when no `grub.cfg` is found.

Unapply bootcmdline settings even when grub.cfg does not exits.

---

man/tuned-adm.8

'tuned-adm profile' accepts more than one profile. Document it in the man page.
Resolves: rhbz#1794337

man: Document the possibility to apply more than one profile

---

profiles/cpu-partitioning/tuned.conf

Reportedly, it's no longer needed.
Resolves: rhbz#1797629

cpu-partitioning: Disable kernel.timer_migration

---

profiles/realtime/tuned.conf

This fixes the unability to use `isolate_managed_irq` from child profiles.

Enable isolate_managed_irq to be defined in child profiles.

---

man/tuned.8

The DOC file specified in the man tuned.8 page may actually be located under the tuned-VERSION of it but there is no indicator that that might be the case.

Adjust FILES section to point to the doc dir  containing the version info

---

92-tuned.install

Currently the 92-tuned.install kernel-install plugin adds the tuned params
to the BLS config files in s390x machines. But the zipl bootloader doesn't
support for environment variables, which leads to cmdlines like following:
root=/dev/mapper/rhel-root crashkernel=auto rd.dasd=0.0.541f rd.dasd=0.0.551f
rd.dasd=0.0.561f rd.dasd=0.0.571f rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap
cio_ignore=all,!condev rd.znet=qeth,0.0.0600,0.0.0601,0.0.0602,layer2=1,portno=0
$tuned_params BOOT_IMAGE=0
Don't modify the BLS snippets ince the zipl bootloader doesn't support the
variables and just exit the script in the s390x case.
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>

Don't modify the BLS snippets on s390x

---

man/tuned-profiles-spectrumscale-ece.7
profiles/spectrumscale-ece/tuned.conf

Hi
This is a profile for Spectrum Scale Erasure Code Edition (ECE) parallel filesystem. It is mainly throughput-performance with the sysctl settings we require customers to set manually to the values set https://github.com/IBM/SpectrumScale_ECE_OS_READINESS/blob/master/sysctl.json
Idea is to offload that manual work into a profile and keep it up to date on tuned as profile in tuned for simplification instead of recommending the changes on the product documentation and checking for individual sysctl values (or other later on) we would document to use the specctrumscale-ece and check that is being used.
Thanks
EDIT: Previous Link was private internal repo, pointing to public now

Spectrum Scale ECE profile

---

.packit.yaml

Hi,
according https://packit.dev/docs/configuration/ packit now supports fedora-all alias and centos-stream for targets.
I tested it on this fake pull request https://github.com/zdohnal/tuned/pull/2 - tests were started for all branched non-EOL (F31+F32) Fedoras, rawhide, epel-8 and centos stream.
Please let me know if I should change something else, otherwise would you mind adding the change to the project?
Thank you in advance!

.packit.yaml: Use fedora-all and centos-stream targets

---

tuned-main.conf
tuned/consts.py
tuned/daemon/application.py
tuned/units/manager.py

There should be a way for administrators and testers to force loading of
architecture specific tuning. For example, if there is some specific tuning
for some platforms with specific CPUIDs and the vendor will release new
compatible platform with the new CPUID, there needs to be a way for
administrator to use the tuning on the new platform without waiting for the
Tuned profile update or without the need to customize the profile.
This commit adds two main config options:
uname_string
cpuinfo_string
If unset (commented), which is the default, runtime detection will be used,
i.e. 'uname' will be called and '/proc/cpuinfo' will be read. If set,
content of the variables will be used instead of the runtime detection.
For example by setting:
uname_string = aarch64
It's possible to pretend that …

Allow override of detected architecture

---

man/tuned-profiles.7
profiles/optimize-serial-console/tuned.conf

Profile which tunes down I/O activity to the serial console by reducing the
printk value. This should make the serial console more responsive.
This profile is intended to be used as an overlay on other
profiles (e.g. throughput-performance profile), example:
```
```
Also minor fixes to the man page quoting.
Resolves: rhbz#1840689

Added new profile optimize-serial-console

---

tuned/plugins/plugin_cpu.py

The 'is' operator is used to determine object identity. What we want to do here instead is a value comparison, i.e. the "==" operator.
With the 'is' operator, the conditions would likely never evaluate to true.
This fixes errors such as these (they seem to get produced during byte
compilation; you can trigger them just by running Tuned).
```
/root/tuned/tuned/plugins/plugin_cpu.py:76: SyntaxWarning: "is" with a literal. Did you mean "=="?
if vendor is "GenuineIntel":
/root/tuned/tuned/plugins/plugin_cpu.py:78: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif vendor is "AuthenticAMD" or vendor is "HygonGenuine":
/root/tuned/tuned/plugins/plugin_cpu.py:78: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif vendor is "AuthenticAMD" or vendor is "HygonGenuine":
```
This …

cpu: Fix string comparisons

---

Makefile
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/conflicting/tuned.conf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/main.fmf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/parent-vars/tuned.conf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/parent/tuned.conf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/parent2/tuned.conf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/post-vars/tuned.conf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/post/tuned.conf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/post2/tuned.conf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/runtest.sh
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/wait_for_signal.py
tuned.spec
tuned/consts.py
tuned/daemon/controller.py
tuned/daemon/daemon.py
tuned/utils/commands.py

This is a minimal viable implementation of a post-loaded profile feature. It was implemented to satisfy the needs of the kernel_settings Ansible role.
https://github.com/linux-system-roles/kernel_settings
This feature allows us to apply a profile in a way that is somewhat separate from the way profiles from the `active_profile` file are applied. Namely, the post-loaded profile is always applied after all the profiles from the `active_profile` (or more precisely, the post-loaded profile is always put to the tail of the profile chain when merging). Also, the post-loaded profile setting is not affected by running `tuned-adm profile <some profile>` - the post-loaded profile remains applied.
The name of the post-loaded profile is stored in `/etc/tuned/post_loaded_profile`.
The lack of support …

Add support for a post-loaded profile

---

profiles/cpu-partitioning/script.sh
profiles/cpu-partitioning/tuned.conf
profiles/realtime/script.sh
profiles/realtime/tuned.conf
tuned/consts.py
tuned/plugins/plugin_irqbalance.py

The irqbalance plugin is a replacement for the bash functions `irqbalance_banned_cpus_setup` and `irqbalance_banned_cpus_clear`. It configures the banned CPUs in /etc/sysconfig/irqbalance. Then it restarts irqbalance (if and only if it was previously running).
The banned CPUs can be specified as a CPU list. For example:
```
[irqbalance]
banned_cpus=2,4,9-13
```
The profiles `cpu-partitioning` and `realtime` have also been updated to use the new plugin.
Resolves: rhbz#1784645

Add irqbalance plugin

---

profiles/throughput-performance/tuned.conf

This adds architecture specific tuning for the Marvell ThunderX and AMD.
It works but I can see few problems with this approach:
1. sysctl are reapplied multiple times - it should be harmless, but it's inefficient.
2. if conflicting settings are used in the arch specific instance and in the base instance, both settings will be applied and the last settings will win - this is not optimal, but it shouldn't cause trouble for unloading, because the units are unloaded in the opposite order as they were loaded.
3. if someone wants to override the arch specific tuning she or he has to override the arch specific instance or has to increase the base instance priority to change the processing order (similarly for the case if the arch specific tuning was defined the first).
I think 1 and 2 are …

Arch specific tuning for Marvell ThunderX and AMD

---

tuned/consts.py
tuned/plugins/plugin_scheduler.py
tuned/utils/commands.py

This is an alpha version, expect bugs :) It needs more love :)
This commit adds cgroup v1 support to the scheduler plugin. It seems that
cgroup v1 is the default on RHEL-8. Systemd uses it there, so we have to start
with the cgroup v1. On Fedora, systemd has been switched
to the cgroup v2 (tested on f31), but it's still possible to intermix there
with the cgroup v1. We can add cgroup v2 support later (the logic of the
extended syntax will not change).
This commit extends the syntax the following way:
```
[scheduler]
cgroup_init=1
cgroup_mount_point=/cgroup/cpuset
cgroup=group
cgroup.group1=2
cgroup.group2=0,2
group.ksoftirqd=0:f:2:cgroup.group1:ksoftirqd.*
ps_blacklist=ksoftirqd.*;rcuc.*;rcub.*;ktimersoftd.*
isolated_cores=1
```
--
Legend:
'cgroup_init' if set to '1' (or similar boolean) …

scheduler: add support for cgroups

---

com.redhat.tuned.policy
tuned/admin/admin.py
tuned/admin/dbus_controller.py
tuned/daemon/controller.py
tuned/daemon/daemon.py

Currently, the post-loaded profile is shown only among regular active profiles. For example:
Current active profile: balanced post
This is not entirely user-friendly, because the user may not know why the post-loaded profile is there, given that they did not specify it in a 'tuned-adm profile' command and given that it's not present in
/etc/tuned/active_profile.
To give the user a hint about this and also to make it easy to see exactly which profile is post-loaded, we make 'tuned-adm active' show the following:
Current active profile: balanced post
Current post-loaded profile: post
This PR additionally fixes a bug with `tuned-adm profile_info`.

[For v2.15] Make tuned-adm indicate which profile is post-loaded

---

INSTALL
requirements.txt
tuned.spec
tuned/daemon/controller.py
tuned/daemon/daemon.py
tuned/utils/profile_recommender.py

Fixes #232
sysfs exports virtual dmi device structs which provides chassis type in numeric form, it should be available in all RHEL6+, so I used it as primary source (not much overhead).
If for some reasons it couldn't be read, dmidecode output will be parsed instead. Removed any references to python-dmidecode module.
chassis type is gathered only once, and only one intance of ProfileRecommender will be created (in daemon).
Signed-off-by: Michal Bajer <outSH@users.noreply.github.com>

Replaced python-dmidecode with reading sysfs dmi and dmidecode tool.

---

profiles/throughput-performance/tuned.conf

It turned out that disablement of the numa_balancing could result in
upto 20% performance drop on some loads.
Related: rhbz#1746957

throughput-performance: fix performance regression on AMD

---

profiles/cpu-partitioning/tuned.conf

E.g. Ubuntu uses /bin/mktemp, while e.g. Fedora uses /usr/bin/mktemp.
There is probably no need to hardcode the path, so rely on the system path.

cpu-partitioning: do not hardcode path to mktemp

---

tuned.spec

spec: make hdparm dependency weak, because it's not available on s390x

---

tuned/plugins/plugin_scheduler.py

It seems cpuset.cpus needs to be initialized before writing to tasks.
Related: rhbz#1784648

scheduler: fix isolated_cores to work with cgroups

---

profiles/realtime-virtual-host/tuned.conf

Like the cpu-partitioning profile, exclude all 'pmd' threads
to avoid repinning ovs-vswitchd pmds.
Resolves: rhbz#1861767
Signed-off-by: Christophe Fontaine <cfontain@redhat.com>

realtime-virtual-host profile: exclude ovs-vswitchd pmds

---

tuned/consts.py
tuned/plugins/plugin_service.py
tuned/utils/commands.py

The service plugin can handle sysvinit, sysv-rc, openrc, systemd.
Syntax is the following:
[service]
service.sendmail = start,enable,file:${i:PROFILE_DIR}/tuned-sendmail.conf
'start' means to start the service, 'stop' to stop, 'enable' to enable,
'disable' to disable, file:FILE is the overlay configuration file
that will be installed for the service. Multiple directives can be
separated by comma ',' or semicolon ';'. If the directives are
conflicting, the last one will be used. The internal variable
${i:PROFILE_DIR} points to the directory from which the profile is
loaded.
The service plugin supports configuration overlays only for the systemd,
for other init systems this directive is ignored. The configuration
overlay files are copied to the /etc/systemd/system/SERVICE_NAME.service.d/ …

Added plugin 'service'

---

tuned.spec

spec: added weak dependency on kmod for modprobe

---

doc/manual/modules/performance/ref_available-tuned-plug-ins.adoc
tuned/plugins/plugin_scheduler.py

The option 'default_irq_smp_affinity' affects what will be written to the
/proc/irq/default_smp_affinity. The option supports the following values:
calc:
Content of the /proc/irq/default_smp_affinity will be calculated from
the 'isolated_cores'. Non-isolated cores are calculated as an inversion
of the 'isolated_cores'. Then the intersection of the non-isolated cores
and the previous content of the /proc/irq/default_smp_affinity is
written to the /proc/irq/default_smp_affinity. If the intersection is
empty set, then just the non-isolated cores are written to the
/proc/irq/default_smp_affinity. This behavior is the default if
option 'default_irq_smp_affinity' is not specified.
ignore:
The /proc/irq/default_smp_affinity is not touched by Tuned.
cpulist like e.g. '1,3-4':
The cpulist is …

scheduler: added default_irq_smp_affinity option

---

92-tuned.install
tuned.spec

Currently the 92-tuned.install kernel-install plugin modifies all
BLS snippets that match the KERNEL_INSTALL_MACHINE_ID passed to
the script.
This makes sense for the system managed entries but it conflicts
with entries that are managed by the boom boot manager: boom will
propagate these options if they are present when the entry is set
up, but the files should not be modified outside boom's control
since this will cause the boom boot identifier to change.
Boom boot entries include the boot_id in the file name pattern:
%{machine_id}-%{boot_id}-%{version}.conf
Compared to the system managed entries which use:
%{machine_id}-%{version}.conf
Modify 92-tuned.install to skip this change for files that match
the boom naming convention.
Rather than rely on the presence of '-' (which may appear in …

Don't modify boom managed BLS snippets

---

tuned/plugins/plugin_service.py
tuned/utils/commands.py

In FIPS MD5 is disabled, thus switch to SHA256 which is available
in FIPS.

service: fixed for FIPS

---

doc/manual/modules/performance/ref_available-tuned-plug-ins.adoc
tuned/plugins/plugin_scheduler.py

Scheduler plugin uses perf event loop to catch newly created processes.
By default it listens to perf.RECORD_COMM and perf.RECORD_EXIT events.
By setting `perf_process_fork` parameter to `true` it will also listen
to perf.RECORD_FORK events, i.e. it will explicitly process
child processes created by the fork system call. Usually, child processes
inherit affinity from their parents, thus the `scheduler` plugin doesn't
need to explicitly process them, that's why the `perf_process_fork`
parameter is by default set to `false` and child processes aren't
explicitly processed. This default setting may also save some CPU time.
Resolves: rhbz#1894610

scheduler: add perf_process_fork option to enable processing of fork

---

tuned/consts.py

Fixing an "issue" pointed out in https://github.com/openshift/cluster-node-tuning-operator/pull/152#discussion_r487690327

Addressing a formatting inconsistency.

---

doc/manual/modules/performance/ref_available-tuned-plug-ins.adoc
tuned/plugins/plugin_scheduler.py

For perf events mmapped buffer is used. Under heavy load the buffer may
overflow. In such cases the `scheduler` plugin may start missing events
and not process some newly created processes. Increasing the buffer size
may help.
The buffer size can be set with the `perf_mmap_pages` parameter.
Value of this parameter has to be power of 2. If it is not the power of 2,
the nearest bigger power of 2 value is calculated from it and this
calculated value is used. If the `perf_mmap_pages` parameter is omitted,
the default kernel value is used, which should be 128 for the recent
kernels (tested on kernel-5.9.8).
Example:
[scheduler]
perf_mmap_pages = 256
Resolves: rhbz#1890219

scheduler: added perf_mmap_pages option to set perf buffer size

---

tuned/plugins/plugin_bootloader.py

bootloader: fixed cmdline duplication with BLS and grub2-mkconfig

---

man/tuned-adm.8

Replaces reference to the non-existent tuned-conf with the correct
manpage (tuned.conf)
Signed-off-by: Jacob Collins <jaco3collins@gmail.com>

Reference the correct manpage

---

profiles/realtime/realtime-variables.conf
profiles/realtime/tuned.conf
tuned/plugins/plugin_net.py
tuned/profiles/functions/function_check_net_queue_count.py

Following patch-set enables tuned to adjust the queue count for
each network device via tuned configuration file. This functionality is
implemented by integrating the ethtool channels control feature with tuned.
This support is essentially required for the real-time setup that has
several isolated but very few housekeeping CPUs. In such environments, it
has been observed that the housekeeping CPUs often run out of vectors when
the IRQs are moved from isolated to housekeeping CPUs. This primarily
happens due to a large number of queues (hence IRQs) creation for each
network device based on all available online CPUs.
With this support added tuned can be configured to adjust the queue count
based on the housekeeping CPUs.
Changelog from v1[1]:
- Replaced get_queue_count with …

Support for adjusting netdev queue count

---

tuned/daemon/controller.py

The current 3600s `wait()` timeout in the controller's loop is too high.  There are known instances of signals not being acted upon.  One known example is `SIGTERM` not being acted upon during system shutdown.  Lowering the timeout to 5s allows for this signal to be acted upon right after the timeout.

Lower the threading.Event's wait() timeout.

---

tuned.spec

make has been removed from BuildRoot and is needed to be add as BuildRequires for new systems.
bz#1900006

Add make as BuildRequires for new fedora and rhel

---

tuned.spec
tuned/plugins/plugin_scheduler.py

schedutils library becomes obsolete in newer versions, so this change allows to use interface in os module where is presented with possibility of usage of schedutils where is not.

Changes to scheduler plugin to support os interface instead of schedutils in newer python versions.

---

.packit.yaml

* rename `centos-stream-x86_64` -> `centos-stream-8-x86_64` because of [this](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/PJT7PK2TLW7T2Z2WLXUGHUYBWR244SBB/)
* remove [upstream_package_name](https://packit.dev/docs/configuration/#upstream_package_name), [downstream_package_name](https://packit.dev/docs/configuration/#downstream_package_name) and [specfile_path](https://packit.dev/docs/configuration/#specfile_path) as the default values should be just fine

 .packit.yaml update

---

tuned/plugins/plugin_net.py

Commit 0ab1f8cc3f87a adds a check which replaces the channels mode parameters
based on the supported mode. With the older kernels, the un-supported mode
was indicated by 0, however recently that has been replaced by a string 'n/a'.
Due to this the check, in plugin_net that verifies if a replacement is
required or not fails.
Fix the check to incorporate this new string that indicates the un-supported
queue mode.
Resolves: rhbz#1943291
Signed-off-by: Nitesh Narayan Lal <nitesh@redhat.com>

plugin_net: Fix check for channels supported mode

---

tuned/plugins/plugin_net.py

Add and improve parameters error checking at the time of their
retrieval and setting respectively in _custom_parameters().
Signed-off-by: Nitesh Narayan Lal <nitesh@redhat.com>

plugin_net: Improve error checking for device parameters

---

profiles/realtime-virtual-guest/script.sh
profiles/realtime-virtual-guest/tuned.conf
profiles/realtime-virtual-host/script.sh
profiles/realtime-virtual-host/tuned.conf
profiles/realtime/script.sh

tuned(8) realtime-virtual-{host|guest} profiles set Kernel and
KVM module parameters via script.sh plugin. These parameters are
to be verified in a verify() function, invoked by tuned-adm verify
command.
* This patch updates verify() functions to validate KVM module
parameters.
* It moves kernel parameters to the tuned.conf file under the
[sysfs] & [sysctl] plugin sections. And removes call to
disable_ksm function, no longer required.
Fixes: RHBZ#1947858

RHBZ#1947858 profiles: improve realtime verify functions

---

doc/manual/modules/performance/ref_tuned-profiles-distributed-with-rhel.adoc

Adding profile descriptions for intel-sst, mssql, hpc-compute, and accelerator-performance profiles that are currently included in the downstream docs. Also included specific information for what the latency-performance, network-throughput, virtual-guest, and virtual-host profiles are made up of.
Related to: rhbz#1935828
Signed-off-by: Jacob Valdez <jvaldez@redhat.com>

adding profile descriptions included in downstream

---

tuned/utils/profile_recommender.py

Previously, if there wasn't dmidecode all 'chassis_type' matches
were ignored. This is not correct, because we cannot enforce
chassis type. Now in such cases the chassis_type is matched
against empty string.
I.e. previously the following matched in case of no dmidecode:
something_that_matched
chassis_type=.*(Notebook|Laptop|Portable).*
Now it doesn't match, but the previous behavior can be still
emulated by e.g.:
something_that_matched
chassis_type=(.*(Notebook|Laptop|Portable).*)|^$
Resolves: rhbz#1959889

recommend: do not ignore chassis_type if there is no dmidecode

---

ci.fmf
tests/beakerlib/Program-tuned-tried-to-access-dev-mem-between/main.fmf
tests/beakerlib/Tuned-takes-too-long-to-reload-start-when-ulimit/main.fmf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/main.fmf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/runtest.sh
tests/beakerlib/error-messages/main.fmf
tests/beakerlib/tuned-adm-functionality/main.fmf

Switch from the deprecated execution method.
Fix for the bz1798183-RFE-support-post-loaded-profile beakerlib test.

ci: beakerlib tests fixes

---

profiles/network-throughput/tuned.conf

Explicitly setting a value for udp_mem does not make sense.
An explicit value does not take into account how much RAM the user's system
has, so setting values here like "12G 16G 64G" works for few specific use
cases but makes no sense for others.
This actually could cause problems if applied on a system with <16G RAM
and UDP protocol usage is allowed to grow as large as it likes, causing
kernel memory pressure in other areas.
Remove these values for now. If still required, a better way to calculate
a larger value based on system RAM can be implemented later.
Signed-off-by: Jamie Bainbridge <jamie.bainbridge@gmail.com>

network-throughput: Remove explicit udp_mem amount

---

profiles/realtime-virtual-guest/realtime-virtual-guest-variables.conf
profiles/realtime-virtual-host/realtime-virtual-host-variables.conf

For realtime KVM host and guests it is important to use housekeeping
CPUs for processing interrupts (IRQs) and network packets transmission.
So that isolated CPUs focus on the -realtime tasks assigned to them.
The 'isolate_managed_irq' and 'netdev_queue_count' variables help
to configure kernels towards this end. Users can define these
variables via tuned(8) configuration files.
Fixes: RHBZ#1817827

RHBZ#1817827 profiles: add isolate_managed_irq & netdev_queue_count variables

---

tests/unit/profiles/test_locator.py
tuned/profiles/loader.py
tuned/profiles/locator.py

The original idea behind this patch is credited to
Jiří Mencák <jmencak@redhat.com>.
Resolves: rhbz#1825882

profiles: fix loading multiple profiles if there are repeating profiles

---

tuned/plugins/plugin_net.py

The conditional for setting a net device parameter has
a faulty order where it can potentially try to first cast a string to int
in a wrong manner and only then check if the value is a specific integer value.
current order:
1. check if a net device has a combined channel containing 0
2. check if a net device has a combined channel containing 'n/a'
fixed order:
robust check to see if device parameter is either 0 or 'n/a'
Signed-off-by: Yanir Quinn <yquinn@redhat.com>

Fix conditional order for setting net device param

---

profiles/functions
profiles/realtime-virtual-host/script.sh

The 'nx_huge_pages' option, will force any executable page mapping to be
performed at 4KiB granularity and requires any existing overlapping
huge-page mapping to be also split in 4KiB chunks[1]. This is due to a HW
bug that doesn't affect our NFV use-cases.
The way a huge-page mapping is dropped is by simply deleting the EPT
entry and flushing TLB caches on all affected CPUs. Next vCPU access to
that address will trigger an EPT_VIOLATION, which will jump into the
host for it to handle the page-fault. In our specific case, this means
all isolated CPUs running oslat will hit an EPT_VIOLATION almost exactly
at the same time. Which is bad enough already, but, given our systems
might have a huge number of isolated CPUs, will also create a lot of
contention over the KVM MMU lock. This has been …

realtime-virtual-host: Disable kvm.nx_huge_pages module option

---

profiles/realtime-virtual-guest/tuned.conf
profiles/realtime-virtual-host/tuned.conf

I/O APIC, one of intel's interrupt controllers, can only change the
affinity on an IRQ line during an EOI (end of interrupt)[1]. In other
words, on boot, although tuned will set a preferred IRQ affinity, it
might not be applied until the next time the interrupt is triggered.
This might be right away, or hours later while oslat or a
latency-sensitive workload is running.
To mitigate this set the 'irqaffinity='kernel command-line[2] option to
match the non-isolated CPU mask when running the realtime-virtual-*
profiles. This way we'll get the right affinity regardless of the
situation stated above.
[1] For more reference see kernel's ioapic_ack_level() function and the
IRQD_SETAFFINITY_PENDING flag.
[2] Actually, this is why irqaffinity was introduced in the first place,
see kernel commit …

realtime-virtual-*: Set irqaffinity through kernel command line

---

profiles/accelerator-performance/tuned.conf
profiles/latency-performance/tuned.conf
profiles/mssql/tuned.conf
profiles/postgresql/tuned.conf
profiles/sap-hana/tuned.conf
profiles/spectrumscale-ece/tuned.conf
profiles/throughput-performance/tuned.conf
profiles/virtual-host/tuned.conf
tuned/plugins/plugin_scheduler.py

New kernels (5.13 and newer) moved some sched_ and numa_ knobs from
the sysctl to the debugfs, thus add and abstract these knobs under the
scheduler plugin. With help of this abstraction it will write
the tuning to the correct place according to the kernel used.
Example:
[scheduler]
sched_migration_cost_ns = 500000
Will work on the old kernel the same way as:
[sysctl]
kernel.sched_migration_cost_ns = 500000
I.e. it will write '500000' to the:
/proc/sys/kernel/sched_migration_cost_ns
And on the new kernel it will write '500000' to the:
/sys/kernel/debug/sched/migration_cost_ns
Also updated TuneD profiles.
Resolves: rhbz#1952687

scheduler: abstract sched_ and numa_ knobs

---

tuned/consts.py
tuned/plugins/plugin_bootloader.py

This makes some changes to address systems that don't support changing
of grub configurations, e.g. embedded systems, where the cmdline is set in
other ways, but we still want to process it and verify against the tuning profile.
* Introduce new option "skip_grub_config". When this is set, no changes to grub
config are attempted. cmdline options are still processed, and the result is
used to verify the current cmdline.
* Improve reporting on expected/found/missing cmdline arguments.
* Add "no_error = True" to the call that reads /etc/default/grub in _bls_enabled().
Signed-off-by: Adriaan Schmidt <adriaan.schmidt@siemens.com>

bootloader: support for systems that don't have grub installed

---

tuned/plugins/plugin_bootloader.py

Currently, `skip_grub_config` and `initrd_remove_dir` options in the
bootloader plug-in are inconsistent.  This commit fixes this issue.
The `skip_grub_config=VALUE` does not change grub configuration if VALUE
is true.  However, cmdline options are still processed, and the result
is used to verify the current cmdline.  Only 'y', 'yes', 't', 'true' and
'1' (case insensitive) are accepted as true values for this option.
Other values are interpreted as false.
Example:
```
[bootloader]
skip_grub_config=True
cmdline=+systemd.cpu_affinity=1
```

bootloader: make skip_grub_config consistent with initrd_remove_dir

---

profiles/functions

Check the presence of `ksm` and `ksmtuned` units before (un)masking them.
Prevents messages in the logs such as:
```
2021-02-24 14:46:52,399 ERROR    tuned.plugins.plugin_script: script '/usr/lib/tuned/cpu-partitioning/script.sh' error output: 'Unit ksm.service does not exist, proceeding anyway.
```

Prevent unnecessary ksm* error log messages.

---

profiles/openshift/tuned.conf

The `[scheduler]` plug-in can be very CPU intensive, especially on the OpenShift platform.  The bug for this issue is tracked by rhbz#1921738. Until this is fixed, work around this problem in the openshift parent profile by adding `runtime=0` `[scheduler]` plug-in option.

openshift profile: workaround high CPU utilization of [scheduler] plug-in

---

tuned/profiles/locator.py

Normally, inclusion of any profile that is not found in profile
directories (`/etc/tuned` and `/usr/lib/tuned`) will fail at profile
application time.
Conditional profile loading can be useful in situations we do not
necessarily expect a certain included profile to exist.  Profile
application failures are undesirable in such cases.  Augment the
TuneD profile hierarchies by adding a functionality to conditionally
include a profile by prefixing its name by '-' symbol.
```
Example:
[main]
summary=An example TuneD profile demonstrating conditional loading
include=-profile1,profile2
```
In this example, the profile "profile1" is conditionally loaded/included
and no error/failure will be reported if the profile does not exist.
Then, the profile "profile2" is unconditionally loaded and errors …

Add conditional profile loading

---

profiles/cpu-partitioning/script.sh
profiles/cpu-partitioning/tuned.conf

…LOAD_BALANCE
Resolves: rhbz#1874596

cpu_partitioning: fixed no_balance_cores on newer kernels

---

tuned/exports/dbus_exporter.py

The code which replaced python-decorator introduced python-2.7
incompatibility. The getfullargspec() from the inspect module is drop in
replacement for the getargspec() and both return the named tuple. Thus
the args member has to be extracted the same way in both cases
(python 2/3).

dbus: fix traceback on python-2.7

---

92-tuned.install

bootloader: on s390(x) remove TuneD variables from the BLS

---

tuned.spec

spec: do not require subscription-manager on CentOS

---

profiles/atomic-guest/tuned.conf
profiles/atomic-host/tuned.conf
profiles/openshift/tuned.conf

raise the netfilter hash table size in openshift/atomic-{host,guest}
to match the max netfilter conntrack entries, reducing such hash
table load.
Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Better conntrack configuration for OCP profiles

---

tuned/plugins/plugin_scheduler.py

To optimize process name matching, the regexes of all groups are combined
into one (r1)|(r2)|..., and after matching the capture is used to determine
which of the original regexes matched. This means that the individual
group regexes must not contain any captures. The current solution replaces
all "(" and ")" with "\\(" and "\\)".
Thus, if we want a group to match "thread(1|2|3)", this will turn into
"thread\\(1|2|3\\)", a regex that matches the three strings "thread(1",
"2" and "3)", which is definitely not what is intended.
This is fixed by instead replacing any "(" by "(?:", making the group
non-capturing. Replacement is not performed if the "(" is preceded by "\\"
or follwed by "?".
Signed-off-by: Adriaan Schmidt <adriaan.schmidt@siemens.com>

scheduler: fix construction of the process name regex

---

tuned.spec

tests: enable unit tests on RHEL-7 (EPEL is needed)

---

tests/unit/utils/test_global_config.py
tuned/gtk/gui_plugin_loader.py
tuned/gtk/gui_profile_loader.py
tuned/gtk/gui_profile_saver.py
tuned/profiles/loader.py
tuned/profiles/locator.py
tuned/profiles/variables.py
tuned/utils/config_parser.py
tuned/utils/global_config.py
tuned/utils/profile_recommender.py

After transit to build in configparser in specific situations it can cause problems. This PR should resolve it.
Resolves #378

Default delimiters errors, inline comments

---

tuned/plugins/plugin_bootloader.py

On systems where /boot dir is not on separate partition grub cannot resolve disk name and cause kernel panic. This is not needed otherwise and can cause kernel panic when disk is renamed.
Resolves: rhbz#2050246

Do not hardcode disk name in tuned initrd path where not needed

---

profiles/openshift/tuned.conf

AWS Nitro instances need special tuning for NVMe devices:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html#timeout-nvme-ebs-volumes
```
[sysfs]
/sys/module/nvme_core/parameters/io_timeout=4294967295
/sys/module/nvme_core/parameters/max_retries=10
```
This tuning should probably be moved to Cloud Provider-specific profiles
once the functionality is implemented.

openshift profile: tuning for NVMe devices

---

profiles/realtime/tuned.conf

We already disable the clocksource watchdog, it's there to double-check
whether clock results are coherent between reads. But a new reliability
test was introduced in recent kernels[1], tracking tsc drift between
CPUs[2]. It works by programming timers on all CPUs, including isolated
ones, and checks whether the tsc was adjusted in between runs. This
introduces unwarranted latency on real time systems. So let's promote
tsc to 'reliable', which disables both checks.
There shouldn't be any impact on old nor new setups. First, this test
didn't exist in the past, so any eventual drift was left uncorrected.
Second, most telco and HPC use-cases will make heavy use of tsc in
user-space, and its reliability is already assumed in the system's
design.
[1] c7719e793478 x86/tsc: Add a timer to make …

realtime: Set tsc as 'reliable'

---

man/tuned-adm.8

Add missing options profile_info, auto_profile and profile mode in the OPTIONS section of the man page.
Resolves: rhbz#2075774
Signed-off-by: Vaibhav Nagare <vnagare@redhat.com>

tuned-adm: Add missing entries in the OPTIONS section

---

man/tuned-adm.8
tuned-adm.bash

Add version/help command automatic complete & Add missing entries in the OPTIONS section
Users can view version/help related commands using the tab key, as convenient as any other procedure，supplementary man file missing option 
Signed-off-by: lilinjie@uniontech.com

Add version/help command automatic complete

---

tuned/plugins/plugin_audio.py
tuned/plugins/plugin_bootloader.py
tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_disk.py
tuned/plugins/plugin_eeepc_she.py
tuned/plugins/plugin_irqbalance.py
tuned/plugins/plugin_modules.py
tuned/plugins/plugin_mounts.py
tuned/plugins/plugin_net.py
tuned/plugins/plugin_rtentsk.py
tuned/plugins/plugin_scheduler.py
tuned/plugins/plugin_script.py
tuned/plugins/plugin_scsi_host.py
tuned/plugins/plugin_selinux.py
tuned/plugins/plugin_service.py
tuned/plugins/plugin_sysctl.py
tuned/plugins/plugin_sysfs.py
tuned/plugins/plugin_systemd.py
tuned/plugins/plugin_usb.py
tuned/plugins/plugin_video.py
tuned/plugins/plugin_vm.py

AsciiDoc documentation for the TuneD plug-ins directly in the source code.  This will allow auto-generation of the TuneD plug-in documentation.  Documenting new plug-ins and plug-in features needs to be compulsory now.

TuneD plug-in documentation.

---

profiles/realtime-virtual-guest/tuned.conf
profiles/realtime-virtual-host/tuned.conf

* add "^\[" to the start of the regexes, so they only match
the intended kernel threads, and not processes that have
the name of a kthread in their cmdline.
* remove unneccessary ".*" at start/end of regexes
Signed-off-by: Adriaan Schmidt <adriaan.schmidt@siemens.com>

profiles: improve regexes to match kernel threads

---

tuned/plugins/plugin_bootloader.py
tuned/utils/commands.py

The following is now parsed differently:
[bootloader]
cmdline =+
Previously it was parsed as operator "=" adding symbol "+" to the cmdline,
now it is parsed as operator "=+" adding empty string "".
For the previous behaviour the leading "+" can now be escaped. It works the
following way:
cmdline =+ -> operator "=+" adding ""
cmdline =\\+ -> operator "=" adding "+"
cmdline =\\\\+ -> operator "=" adding "\\+"
Non leading escaping is ignored, e.g.:
cmdline =ab\\+ -> operator "=" adding "ab\\+"
Similarly for the operator "=-".
Also the arguments are now correctly escaped when further processed by
TuneD and the following problems should be now fixed:
cmdline =\n -> corruption of the /etc/tuned/bootcmdline with newlines
cmdline =\k -> TuneD traceback
cmdline =\1 -> operator "=" adding …

bootloader: cmdline parser change and fixed escaping

---

profiles/cpu-partitioning/cpu-partitioning-variables.conf
profiles/realtime-virtual-guest/realtime-virtual-guest-variables.conf
profiles/realtime-virtual-host/realtime-virtual-host-variables.conf
profiles/realtime/realtime-variables.conf
tuned/consts.py
tuned/profiles/functions/function_calc_isolated_cores.py

The calc_isolated_cores function expands to the list of cores to
isolate. It accepts optional argument which specifies how many cores
from each socket reserve for housekeeping. If not specified, one core
from each socket is reserved for housekeeping.
Example:
Machine with 2 sockets, each 4 cores, using the following user variable
configuration file, e.g. /etc/tuned/realtime-variables.conf:
isolated_cores=${f:calc_isolated_cores:2}
It will expand to:
isolated_cores=2, 3, 6, 7
I.e. cores 0, 1 and 4, 5 will be used for housekeeping.
Resolves: rhbz#2093847

builtin functions: added calc_isolated_cores function

---

.packit.yaml

We have made a few changes to packit.yaml syntax - so that yours is up to date.
The most important change is the switch to building SRPMs in Copr which is our long-term plan. That should fix the el7 build problems right now.

Packit yaml improvements

---

profiles/openshift/tuned.conf

The kernel tunable `fs.aio-max-nr` specifies the maximum number of events specified on the `io_setup()` call for all currently active aio contexts.  On large systems this causes issues with the userspace `io_setup()` call failing with `EAGAIN`.  Libvirt already increases this setting to 1048576:
https://github.com/libvirt/libvirt/blob/96e99e49483de4fb293ce26691cbce19110fb3a9/src/remote/libvirtd.sysctl
The only potential drawback of a larger limit is that a malicious users could issue parallel `io_setup()` requests to cause the kernel to set aside memory.

Profile openshift: increase fs.aio-max-nr tunable

---

tuned/exports/dbus_exporter.py

As *args is tuple we cannot change its values. This cause exception for example when calling dbus without sudo and fallback for tuned-adm, but this behavior at least confusing.

Fix in polkit authorization.

---

profiles/realtime-virtual-guest/tuned.conf
profiles/realtime-virtual-host/tuned.conf

The PREEMPT_RT upstream tree [1] is reintroducing a per-CPU kthread for handling timer expiry named ktimers/${cpu}, and RHEL-RT is following this approach [2].
The recommended priority tuning for that kthread is to simply match that of ksoftirqd, which is what is implemented here.
Note that ktimersoftd is the predecessor of ktimers, and isn't present on RT kernels newer than v5.0.19-rt11 / RHEL-RT 7.
[1]: https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=2122220
Resolves: rhbz#2122220
Signed-off-by: Valentin Schneider <vschneid@redhat.com>

realtime-virtual-*: Tune priority of new ktimers threads

---

profiles/openshift-control-plane/tuned.conf

According to testing done by the kernel QE and performance teams,
the sched_* tunables should be dropped in several profiles.
The openshift-control-plane profile is based on other profiles
which have already dropped these tunables (network-latency,
throughput-performance). 
@yarda We would like to drop these tunables on RHEL9, but keep them on RHEL8. is it possible with a patch to ensure this change only takes effect on RHEL9, at least for the FDP builds that will feed into the Node Tuning Operator?
/cc @jmencak

profiles: drop sched_ tuning from openshift-control-plane

---

README

Add missing options profile_info, auto_profile and profile mode in the OPTIONS section of the README.
Signed-off-by: lilinjie <lilinjie@uniontech.com>

Add missing entries in the OPTIONS section

---

profiles/hpc-compute/tuned.conf

In the old kernels, `vm.hugepages_treat_as_movable tunable` was aimed at reducing memory fragmentation.  Things have changed since then and this tunable is no longer present in recent kernels:
https://lore.kernel.org/lkml/20171003072619.8654-1-mhocko@kernel.org/t/
Its presence in the hpc-compute profile causes TuneD to log errors. Remove it.

hpc-compute profile: Remove vm.hugepages_treat_as_movable

---

tuned.service

The polkit has D-bus activation thus it will be activated on demand and we don't need to explicitly activate it.
Resolves: rhbz#2065591

systemd: relax polkit requirement

---

contrib/sysvinit/tuned
profiles/functions

It's kept for legacy purposes, but the path should be correct.
Resolves: rhbz#2118301

Fixed sysvinit path

---

tuned/profiles/loader.py

This was caused by wrong inheritance of exceptions.
Resolves: rhbz#2071418

Fix for catching exceptions in profile loader.

---

Makefile
man/tuned-profiles-cpu-partitioning-powersave.7
profiles/cpu-partitioning-powersave/cpu-partitioning-powersave-variables.conf
profiles/cpu-partitioning-powersave/tuned.conf
tuned.spec

The new profile sets the intel_acpi driver to passive mode to be able to set the standard acpi governors (ondemand/userspace) and provides more flexibility on the C-states, as it is exposed as a new variable.
Signed-off-by: Christophe Fontaine <cfontain@redhat.com>

Add new cpu-partitioning-powersave profile

---

tuned/plugins/plugin_bootloader.py

Even when we instruct TuneD to not apply changes to the bootloader config (skip_grub_config=true) it's useful to expose the generated cmdline. External tools could then read TuneD's desired cmdline, and adapt configurations of (so far) unsupported bootloaders like systemd-boot.
Signed-off-by: Adriaan Schmidt <adriaan.schmidt@siemens.com>

bootloader: create bootcmdline even when skip_grub_config=true

---

com.redhat.tuned.policy
tuned/daemon/controller.py
tuned/plugins/hotplug.py
tuned/plugins/plugin_audio.py
tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_net.py
tuned/profiles/functions/function_cpulist2devs.py
tuned/utils/commands.py

Extends the runtime API by the method:
```
instance_acquire_devices(devices, instance_name)
```
E.g. consider the following TuneD profile:
```
[cpus_perf]
type=cpu
devices=cpu0, cpu1
governor=performance
[cpus_idle]
type=cpu
devices=${f:cpulist2devs:2-3}
governor=ondemand
[cpus_idle2]
type=cpu
devices=${f:cpulist2devs:4-5,7}
governor=ondemand
```
Notice that it's possible to use internal function 'cpulist2devs' to easily
specify cpulists.
After the following API call:
```
instance_acquire_devices("cpulist:2-5,7", "cpus_perf")
```
It will result in cpu0 - cpu5 and cpu7 having the "performance" governor.
It's also possible to specify full device names in the API instead of the
cpulist, e.g.:
```
instance_acquire_devices("cpu2,cpu3,cpu4,cpu5,cpu7", "cpus_perf")
```
In case the comma is part …

API: add support for moving devices between instances

---

Makefile

Helpful if you have an arch-prefixed pkg-config, e.g. when cross compiling.
Signed-off-by: Heiko Becker <heirecka@exherbo.org>

Allow selecting a different pkg-config executable

---

tuned/gtk/gui_plugin_loader.py
tuned/gtk/gui_profile_loader.py
tuned/gtk/gui_profile_saver.py
tuned/profiles/loader.py
tuned/profiles/locator.py
tuned/profiles/variables.py
tuned/utils/config_parser.py
tuned/utils/global_config.py
tuned/utils/profile_recommender.py

Now it should allow duplicate options and sections in the INI files, the latest value is taken, the previous values are ignored, e.g.:
[selinux]
avc_cache_threshold=4096
avc_cache_threshold=8192
The avc_cache_threshold will be set to the 8192.
Related: rhbz#2071418

configparser: use no strict parser to mimic old behavior

---

profiles/throughput-performance/tuned.conf

throughput-performance: set net.core.somaxconn to at least 2048

---

tuned/plugins/plugin_scheduler.py

perf module does not close it's file descriptors and it seams there is no better/nicer interface in python.
Resolves: rhbz#2080227

Closing fd from perf module in scheduler plugin

---

tuned/plugins/plugin_cpu.py

Adding pm_qos_resume_latency_us option for cpu plugin.

---

tuned-main.conf
tuned.py
tuned/admin/admin.py
tuned/consts.py
tuned/daemon/application.py
tuned/daemon/controller.py
tuned/daemon/daemon.py
tuned/exports/__init__.py
tuned/exports/controller.py
tuned/exports/interfaces.py
tuned/exports/unix_socket_exporter.py
tuned/utils/global_config.py

TuneD is listening on paths specified in config in option unix_socket_paths and send signals to paths in option unix_socket_signal_paths. Example call:
ssock_file = "/tmp/tuned_socket"
csock_file = "/tmp/tuned_socket_client"
if os.path.exists(csock_file):
os.remove(csock_file)
s=socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM) s.bind(csock_file)
try:
s.sendto(pickle.dumps(("switch_profile", "balanced")), ssock_file)
print(pickle.loads(s.recvfrom(4096)[0]))
except Exception as e:
print("E: %s" % e)
s.close()
This PR also introduce possibility to disable dbus API in main TuneD config.
Resolves: rhbz#2113900

Expose TuneD API to the Unix Domain Socket.

---

tuned/plugins/plugin_scheduler.py

Fixing no _evlist attribute when run without daemon

---

tuned/plugins/plugin_sysctl.py

PR492 introduced reporting on reapplied sysctls.  While it is a useful functionality to get notified about potential conflicts between filesystem-level and TuneD-level settings, it can generate a lot of noise when these settings are equal.  Report reapplied sysctls only when filesystem-level and TuneD-level settings differ.

Report reapplied sysctls only on different values

---

tuned/admin/admin.py

As a sideeffect of 08b348b7a4b1a5d94bea160fecea4a2759b01a9d we got strange error messages for unauthorized switch_profile requests. This commit tries to improve it.

tuned-adm: better error message for unauthorized switch_profile

---

Makefile
tuned.spec

/etc is for local overrides, not for package-shipped policies

install dbus policy in /usr/share/dbus-1

---

tuned-gui.py

otherwise we just get the "image missing" icon

set the icon in the about dialog

---

experiments/powertop2tuned.py
profiles/cpu-partitioning/00-tuned-pre-udev.sh
profiles/cpu-partitioning/script.sh
profiles/functions
profiles/laptop-ac-powersave/script.sh
profiles/powersave/script.sh
profiles/realtime-virtual-guest/script.sh
profiles/realtime-virtual-host/script.sh
profiles/realtime/script.sh
profiles/spindown-disk/script.sh

`/bin/sh` is bash on Red Hat/Fedora, but other distributions (especially Debian/Ubuntu based ones) have other (POSIX compatible) shells there. Let's explicitly use `/bin/bash` for things that use bash features (the `functions` file uses some, for example).

explicitly use /bin/bash for tuned scripts

---

doc/manual/modules/performance/proc_creating-new-tuned-profiles.adoc
doc/manual/modules/performance/proc_installing-and-enabling-tuned.adoc
doc/manual/modules/performance/proc_modifying-existing-tuned-profiles.adoc
doc/manual/modules/performance/proc_setting-a-tuned-profile.adoc
man/tuned-adm.8
tuned/admin/admin.py

Also added the -i and --ignore-missing options to the tuned-adm manual page.
Related: rhbz#2075827

tuned-adm: fix typo in the verification output

---

profiles/openshift/tuned.conf

With openshift/machine-config-operator#3676 we removed globally setting ip forwarding in MCO. We should not be setting it in the default profile for OpenShift. We now set it on a per interface basis as needed. However, by setting proc/sys/net/ipv4/forward rather than (forwarding) it will reset all the values:
"This variable is special, its change resets all configuration parameters to their default state (RFC1122 for hosts, RFC1812 for routers)"
We suspect this causes upgrade to fail. NTO sets this to 1, which then resets all the per interface config that OVNK wrote. Then during upgrade when there is a tuned profile change, the config change is rolled back so forward is 0, and now there is no connectivity to kapi and upgrade fails.

OCPBUGS-14247: Remove setting ip forwarding via openshift profile

---

tuned/plugins/plugin_scheduler.py

Fix logging in [scheduler] plug-in

---

tuned-main.conf
tuned/consts.py
tuned/daemon/controller.py
tuned/daemon/daemon.py
tuned/plugins/base.py
tuned/plugins/instance/instance.py
tuned/plugins/plugin_bootloader.py
tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_modules.py
tuned/plugins/plugin_scheduler.py
tuned/plugins/plugin_script.py
tuned/plugins/plugin_service.py
tuned/plugins/plugin_sysctl.py
tuned/plugins/plugin_sysfs.py
tuned/plugins/plugin_systemd.py
tuned/units/manager.py

Add rollback option to tuned-main.conf file.  The option specifies how
TuneD should perform rollbacks.  By default, the old behaviour is
preserved (rollback=auto) and settings are rolled back on TuneD daemon
exit and profile switches.  Using rollback=not_on_exit will result in
TuneD not performing any rollbacks on the daemon exit, however, on
profile switches, settings rollbacks will still be performed.
Resolves: rhbz#2203142

Add rollback_on_exit option

---

tuned/plugins/plugin_net.py

plugin_net: expand variables properly
When attempting verification for the realtime profile, the following error was observed:
ERROR    tuned.plugins.plugin_net: unknown channels parameter(s): {'check_net_queue_count'}
This seems to be because this line:
channels=combined ${f:check_net_queue_count:${netdev_queue_count}} in /usr/lib/tuned/realtime/tuned.conf is not correctly parsed.
This should be evaluated out to "channels=combined N", where "${f:check_net_queue_count:${netdev_queue_count}}" is replaced by the value of netdev_queue_count in /etc/tuned/realtime-variables.conf.
However, the observed error is becaused this line is split on delimiters such as ':', and the whole thing gets jumbled up - instead of evaluating the function to a number.
We fix can this issue by properly evaluating …

plugin_net: expand variables properly

---

tuned-gui.py

Signed-off-by: lilinjie lilinjie@uniontech.com
add error dialog when no active profile set
&&
error_dialog() missing 1 required positional argument: 'info'

add error dialog when no active profile set

---

tuned/profiles/functions/function_calc_isolated_cores.py

Show no errors when the physical_package_id file does not exist -- the CPUs may be offline.
Resolves: rhbz#2217015

No errors when physical_package_id file does not exist

---

profiles/functions

When ksm or ksmtuned services do not exist, return 0 so that we do not generate ERRORs in TuneD logs.
Resolves: OCPBUGS-19656

Return 0 when ksm services do not exist

---

tuned/plugins/plugin_cpu.py

Mixed indentation, tabs and spaces. Python does not mind, but Code/Pylance complains about it:

style: fix inconsistent whitespace in plugin_cpu.py

---

tuned/utils/commands.py

Improve error log by printing all arguments passed to command. 
This helps in troubleshooting issues where just knowing the command is not enough, we need more details on which settings, devices and options has caused this error.
Without fix:
~~~
ERROR    tuned.utils.commands: Executing ethtool error: netlink error: requested channel count exceeds maximum (offset 40)
~~~
With fix:
~~~
From logs we can easily identify the complete command which failed, this would also show us the device name.
ERROR    tuned.utils.commands: Executing ethtool -L ens3 combined 2 error: netlink error: requested channel count exceeds maximum (offset 36) netlink error: Invalid argument 
~~~

RHEL-3689: Print all arguments of failing command in err_msg

---

tuned/plugins/plugin_sysctl.py
tuned/utils/commands.py

The logic for converting sysctl name to path did not work for sysctls like:
[sysctl]
net.ipv4.conf.bond0/355.forwarding=1

RHEL-3707: Add support for sysctl names with slash

---

man/tuned-adm.8
tuned-adm.py
tuned/admin/admin.py
tuned/admin/dbus_controller.py

Resolves: RHEL-15141
Until now, this was only possible by manually sending a message to TuneD via the DBus API.

Add a tuned-adm command for moving devices between plugin instances

---

tuned/plugins/plugin_bootloader.py
tuned/plugins/plugin_net.py
tuned/plugins/plugin_scheduler.py
tuned/profiles/functions/functions.py
tuned/utils/commands.py
tuned/utils/config_parser.py
tuned/utils/nettool.py

Python 3.12 is more strict about correct escaping and outputs SyntaxWarning for invalid escape sequences that were previously silently corrected.

Fixed REs escape sequences not to trigger SyntaxWarning

---

profiles/cpu-partitioning/cpu-partitioning-variables.conf
profiles/realtime-virtual-guest/realtime-virtual-guest-variables.conf
profiles/realtime-virtual-host/realtime-virtual-host-variables.conf
profiles/realtime/realtime-variables.conf

Just explain what isolated_cores= is for and recommend to only have one isolated_cores= line to avoid wrong system configuration.

profiles: Improve 'isolated_cores=' help text

---

profiles/balanced/tuned.conf
profiles/powersave/tuned.conf
profiles/server-powersave/tuned.conf
profiles/throughput-performance/tuned.conf

This commit adds 'energy_performance_preference' tunings for some of the premade profiles in TuneD. For more information about energy_performance_preference, see https://www.kernel.org/doc/html/v4.19/admin-guide/pm/intel_pstate.html#energy-vs-performance-hints
Resolves https://github.com/redhat-performance/tuned/issues/563
Supersedes https://github.com/redhat-performance/tuned/pull/565
This PR adds `energy_performance_preference` hints to profiles in TuneD.
Setting EPP hints on systems that support `intel-pstate` and `amd-pstate` drivers can significantly reduce power consumption. For example, `power-profiles-daemon` supports energy_performance_preference hints, but currently suffers from an issue where multiple drivers cannot be used at once, therefore `platform-profile` takes precedence …

profiles: add energy_performance_preference hints to profiles

---

tuned/plugins/plugin_sysctl.py

When applying system sysctl options, we log when the applied option overrides an option from a TuneD config. The overrided option may be provided as a variable, so we have to expand it before comparing it with the applied option.
Resolves: RHEL-18972

Expand sysctl plugin options when reporting overrides

---

tuned/plugins/plugin_bootloader.py

If delete and append kargs args are the same in the same order there is no functional differences so we can safely skip calling rpm-ostree kargs and avoid creating a new rpm-ostree deployment.
Resolves: RHEL-20767
Fixes #585

Skip calling rpm-ostree kargs in no-op case

---

Makefile
tuned-ppd.py
tuned.py
tuned.spec
tuned/consts.py
tuned/daemon/application.py
tuned/exports/__init__.py
tuned/exports/controller.py
tuned/exports/dbus_exporter.py
tuned/exports/dbus_exporter_with_properties.py
tuned/ppd/config.py
tuned/ppd/controller.py
tuned/ppd/dbus.conf
tuned/ppd/ppd.conf
tuned/ppd/tuned-ppd.dbus.service
tuned/ppd/tuned-ppd.policy
tuned/ppd/tuned-ppd.service

This PR (currently draft) will introduce a PPD-to-TuneD API translation daemon. Feel free to comment on the implementation during the development process.

PPD-to-TuneD API translation daemon

---

profiles/functions

This change does not attempt to `_wifi_set_power_level()` unless `/proc/net/wireless` exists.
Other changes: fix a typo.

Do not report errors on systems with no wifi

---

tuned/plugins/plugin_intel_uncore.py

Add simplistic intel uncore plugin to so that uncore maximum and minimum frequency can be set.
For example lowering uncore maximum frequency can have significant impact on the total power consummation of SoC.
Refer to the following link to get details:
https://docs.kernel.org/admin-guide/pm/intel_uncore_frequency_scaling.html
When system with TPMI (Topology Aware Register and PM Capsule Interface) is detected only devices configured via TPMI are used, since configuring via deprecated (package/die) interface create conflict on new systems.
Plugin allow to configure frequency per individual uncore units, example profile config options can look like this:
[intel_uncore_all0] # power save
type=intel_uncore
devices=uncore0*
max_freq_khz=2000000
[intel_uncore_10] # performance
type=intel_uncore …

Add intel uncore plugin

---

Makefile

Fixes: 3e03b8b Configure the PPD-to-TuneD daemon to work as a replacement of PPD
Signed-off-by: Mario Limonciello <mario.limonciello@amd.com>
Closes: https://github.com/redhat-performance/tuned/issues/597

Add missing install command for tuned-ppd.py

---

tuned-main.conf

Dynamic tuning is PoC implementation and it can cause many problems especially with some networks drivers where it can interrupt network connections and also with modern CPUs where it can worsen power consumption by limiting CPUs from entering deeper C-states. Now, when TuneD is going to replace power-profiles-daemon these problems can accumulate and cause bad user experience.
RHEL disables dynamic tuning downstream for a long time, so follow it and also disable it by default upstream. People who knows what they are doing can still enable it.
Fixes #588

Disable dynamic tuning by default

---

doc/manual/modules/performance/ref_built-in-functions-available-in-tuned-profiles.adoc
tuned/profiles/functions/function_intel_recommended_pstate.py

Added intel_recommended_pstate builtin function which reads the processor name from pmu file under `/sys/devices`, and returns correct pstate value.
Intel recommends to use the intel_pstate CPUFreq driver in active mode with HWP enabled on Ice Lake and later generations processors.This feature allows dynamically setting intel_pstate based on the processor's model. Currently, users need to create a tuned override if they want to set intel_pstate to active even for newer generation processors. For older generation processors setting pstate to active can introduce jitters which were historically seen around and tested with RHEL-7.4.From IceLake generation, intel has fixed these issues.
- With this builtin function it is possible to write now:
```
[variables] …
```

Added intel_recommended_pstate builtin function.

---

doc/manual/modules/performance/con_the-location-of-tuned-profiles.adoc
tuned-adm.py
tuned-gui.py
tuned-main.conf
tuned/admin/admin.py
tuned/consts.py
tuned/daemon/application.py
tuned/exports/unix_socket_exporter.py
tuned/gtk/gui_profile_loader.py
tuned/utils/global_config.py

The new default directory for user-defined profiles is `/etc/tuned/profiles/`; other directories can be specified via the `custom_profile_dirs` option in `tuned-main.conf`.
When updating the TuneD package, existing profiles in `/etc/tuned/` are automatically copied to `/etc/tuned/profiles/`, unless there are conflicts.
GUI also needed to be updated - I only did the bare minimum for it to work, more major refactoring deserves a separate PR.

Add the option to specify custom directories with user-defined profiles

---

tuned/plugins/plugin_modules.py

this fixes tuned verification when configuring module parameters such as:
onload=cplane_server_params=--affinity=0x100000000
Tuned correctly sets them like this:
$ cat /etc/modprobe.d/tuned.conf
options onload cplane_server_params=--affinity=0x100000000
$ cat /sys/module/onload/parameters/cplane_server_params
--affinity=0x100000000
However, before this change tuned reports verification failure whenever a parameter value contains an equal sign.

Allow equal characters in kernel module parameter value

---

tuned/plugins/plugin_irq.py

To optimize latencies in realtime applications, we have a need to direct certain interrupts to certain cpus running our realtime processes. In addition, the cpu allocation happens dynamically (e.g., applications deployed as containers).
There's two parts to this:
- Handle interrupts individually: current implementation of the `scheduler` plugin can only set affinities of ALL interrupts.
- Set the affinities dynamically: current implementation requires the affinity to be set statically in the profile.
This PoC
- Adds a new plugin `irq`, which treats interrupts as "devices", so we can have multiple plugin instances, each with different affinities, and each tuning different irqs.
- Adds functions to dynamically create and destroy plugin instances. This way, when a new application is started, …

Tuning of individual interrupts

---

com.redhat.tuned.policy
tests/unit/plugins/test_base.py
tuned/daemon/controller.py
tuned/plugins/base.py
tuned/plugins/instance/instance.py
tuned/profiles/unit.py
tuned/units/manager.py

add dbus commands for dynamic creation of instances

---

Makefile
doc/manual/modules/performance/con_inheritance-between-tuned-profiles.adoc
doc/manual/modules/performance/con_the-location-of-tuned-profiles.adoc
doc/manual/modules/performance/proc_creating-new-tuned-profiles.adoc
doc/manual/modules/performance/proc_modifying-existing-tuned-profiles.adoc
doc/manual/modules/performance/proc_setting-the-disk-scheduler-using-tuned.adoc
man/tuned-adm.8
man/tuned-profiles.7
man/tuned.conf.5
tests/beakerlib/Traceback-caused-by-scheduler-plugin-with/runtest.sh
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/runtest.sh
tests/beakerlib/bz2071418-TuneD-exits-on-duplicate-config-lines-new/runtest.sh
tests/beakerlib/error-messages/runtest.sh
tests/beakerlib/variables-support-in-profiles/runtest.sh
tuned-adm.bash
tuned-main.conf
tuned.spec
tuned/consts.py

This PR changes the default locations of user and system profiles to `/etc/tuned/profiles/` and `/usr/lib/tuned/profiles/`, respectively. In Fedora and RHEL 10, existing user-defined profiles should also be automatically migrated.
Only the last commit of the PR is relevant for review, as it will be rebased onto #609.

Migrate profiles to /etc/tuned/profiles/ and /usr/lib/tuned/profiles/

---

profiles/balanced-battery/tuned.conf
tuned/ppd/config.py
tuned/ppd/controller.py
tuned/ppd/ppd.conf

power-profiles-daemon has the ability to detect battery change events using upower and to apply different tuned settings based upon whether plugged into power or not.
In PPD this is used specifically to set the energy performance preference differently in the 'balanced' profile, but there is no reason that this concept can't actually apply to all profiles.
Add support for detecting battery change events and apply a profile specified in `ppd.conf` for battery in the different PPD states.
CC @smallorange

tuned-ppd: Detect battery change events

---

tuned/daemon/controller.py
tuned/daemon/daemon.py

daemon: buffer sighup signal

---

tuned/plugins/plugin_cpu.py

The feature depends on kernel configuration (CONFIG_CPU_IDLE). While this seems to be commonly enabled on x86, we've seen ARM systems where it's disabled, and in this case it's perfectly valid for /dev/cpu_dma_latency to be missing.
Since we cannot opt-out of the PM QoS feature in the cpu plugin, this case should not be an error.

plugin_cpu: decrease the severity of _has_pm_qos==False

---

tuned/profiles/functions/function_log.py
tuned/profiles/functions/functions.py

E.g.:
[variables]
dummy=${f:log:${f:exec:uname}}
Logs the output of the 'uname' command to the TuneD log.
Also added more verbose debug output which can help with functions debugging. Enable with 'tuned -D'.

functions: added 'log' which helps with debugging

---

profiles/accelerator-performance/tuned.conf
profiles/balanced/tuned.conf
profiles/latency-performance/tuned.conf
profiles/powersave/tuned.conf
profiles/throughput-performance/tuned.conf
tuned/plugins/plugin_video.py

This attribute accepts a range from 0 through 4 where larger values will also have larger panel power savings.
Using this has a trade off for color accuracy, and it is only applied when the system is currently operating on battery.
The plugin uses upower to get a signal when battery changes so that it will react instantly.
Intentionally the plugin will check what values are already programmed to the sysfs file to avoid unnecessary writes.  Writing the sysfs file will cause a modeset which isn't necessary if writing the same value twice.
The default values are applied to the profiles that are used in power-profiles-daemon compatbility.  They also match the values used in that software.

Add a plugin for amdgpu tuning of the `panel_power_savings` attribute

---

tuned-adm.py
tuned/admin/admin.py

When TuneD is off, and a profile is applied using `tuned-adm profile`, the command attempts to start it. Before this change, the profile would always be applied via the `active_profile` file.
When TuneD supports DBus, we can change the profile via a DBus call instead, and thus get information about the result. After the restart, I therefore added a new check which determines whether TuneD is on the dbus. If it's not, we fallback to the original profile activation.
The only disadvantage of this approach is that TuneD is restarted twice in the unlikely scenario that both `enable_dbus` and `daemon` are turned on, but TuneD does not become active on the DBus after a restart. This would, however, signalize some misconfiguration because if the TuneD service unit has `type=dbus` set, restarting …

Re-check dbus when (re)starting TuneD from tuned-adm profile

---

tuned/ppd/controller.py

Having used tuned-ppd by default for a couple of months, I've discovered a couple of bugs that should be resolved by this PR.

Bug fixes in tuned-ppd

---

profiles/throughput-performance/tuned.conf

Leftover from c6d6fdcc4c944df9998e0ebe75f31cc8aed452c1

throughput-performance: dropped unused AMD related variable

---

tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_sysctl.py
tuned/plugins/plugin_sysfs.py
tuned/utils/commands.py

This PR adds a new option `check_diff` to the function `commands.write_to_file`. When set to `True`, the function checks whether the current value is equal to the one being written - if it is, the write is skipped.
The new option is disabled by default, but I enable it for plugin options where the write may cause an inter-processor interrupt even when the value does not change.

Avoid unnecessary inter-processor interrupts by checking that writes are necessary

---

tuned/plugins/plugin_disk.py

The disk plugin checks each device for hdparm
support during initialization. When using many disk devices, this can lead to unwanted delays in profile application.
This change makes the hdparm check lazy by postponing it to the moment when hdparm is actually needed, i.e., during dynamic tuning or when setting spindown/apm. Each device is checked at most once - the plugin now stores the sets of hdparm-supported devices and hdparm-unsupported devices).
Resolves: RHEL-6891

Disk plugin: make hdparm device checks lazy

---

tuned/daemon/application.py
tuned/daemon/controller.py
tuned/exports/dbus_exporter.py
tuned/hardware/inventory.py
tuned/plugins/base.py
tuned/plugins/plugin_acpi.py
tuned/plugins/plugin_bootloader.py
tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_disk.py
tuned/plugins/plugin_irqbalance.py
tuned/plugins/plugin_modules.py
tuned/plugins/plugin_net.py
tuned/plugins/plugin_scheduler.py
tuned/plugins/plugin_video.py
tuned/plugins/plugin_vm.py
tuned/profiles/functions/function_check_net_queue_count.py
tuned/utils/profile_recommender.py

Always use warning(), as warn() has been removed from Python with v3.13.

chore: remove use of deprecated Logger.warn()

---

tuned/profiles/functions/function_lscpu_check.py

- This is similar to the cpuinfo function that reads from /proc/cpuinfo
- Unfortunately that function was insufficient for our needs as we need to identify both the Vendor and Architecture reliably

CNF-13015: Add helper function to run `lscpu` and parse result using regex parameters

---

tuned/plugins/plugin_uncore.py

Using direct frequency values in only useful in specialistic profiles
where we know target platform. Allow to configure uncore frequency as
percent of hardware maximum/minimum frequency. Such parameters can be
used in generic profiles like 'balanced' in portable way, for example:
[uncore]
max_freq_khz=90%

uncore: Allow to configure frequency limits using percent

---

tuned/profiles/functions/function_package2cpus.py
tuned/profiles/functions/function_package2uncores.py

Allow to specify cpus and uncores based on package (socket) number.

Add package to {cpus,uncores} matching functions

---

tuned/consts.py
tuned/hardware/inventory.py

This is the first shot trying to resolve the potential problem with hotplug. It needs thorough testing. I am not sure whether it's a good thing to use it also for the remove events, maybe it would require refactor.

hotplug: wait for device initialization

---

tuned-ppd.py
tuned.spec
tuned/consts.py
tuned/ppd/controller.py
tuned/ppd/tuned-ppd.service

This PR introduces small changes in and related to `tuned-ppd`:
- The daemon now has the option to log output into a file (the default is `/var/log/tuned/tuned-ppd.log`).
- The PID option was removed from the systems service file: the daemon currently does not write its PID anywhere.
- The spec file is adjusted to include standard systems scriptlet macros according to [Fedora guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_systemd).
- When swapping `power-profiles-daemon` for `tuned-ppd`, scriptlets now check whether PPD is running and if yes, `tuned-ppd` is also started right away.

Tuned ppd adjustments

---

tuned/plugins/plugin_audio.py

It fixes Nvidia suspension for laptops.
https://linrunner.de/tlp/settings/audio.html#sound-power-save-on-ac-bat

Enable controller reset for audio by default

---

tests/beakerlib/error-messages/runtest.sh
tests/beakerlib/variables-support-in-profiles/runtest.sh

Some minor test adjustments:
- All other tests run `tunedDisableSystemdRateLimitingStart` without `rlRun`, so stick to it in `variables-support-in-profiles`, too.
- Add a missing `rlServiceRestore` to the `error-messages` test. This fixes [recent test failures](https://artifacts.dev.testing-farm.io/e67c22b9-4ea9-4be6-8cf1-ad060d839fd3/) in Rawhide, most likely triggered by the recent [addition of TuneD to systemd presets](https://src.fedoraproject.org/rpms/fedora-release/pull-request/335).

Beakerlib tests adjustments

---

Makefile

This change was forgotten during #644, therefore causing errors when running `make rpm`.

Add `functions` to the files copied by the release-cp Makefile target

---

profiles/balanced-battery/tuned.conf
profiles/balanced/tuned.conf
profiles/powersave/tuned.conf
tuned/plugins/plugin_cpu.py

Core performance boost control is added to kernel 6.11. This sets up the policy to turn it off while in the power saver profile.
Link: https://lore.kernel.org/linux-pm/1a78eeaa-fadd-4734-aaeb-2fe11e96e198@amd.com/T/#m4a0c8917ea8fb033504055bd61512c80c85410c8

Add support for controlling amd-pstate core performance boost

---

tuned/plugins/plugin_irq.py

Forgot to expand variables in the new `irq` plugin.
Side question: is there a reason that variables in options are not automatically expanded, e.g. right after loading the profile? They are automatically expanded for `@command` invocations, but not for the "general" non-command tuning.

fix: expand variables in plugin_irq

---

tuned/plugins/plugin_scheduler.py

Failing to change the affinity of a defunct process should not cause any issues, even if the process is not bound to specific CPUs. We should thus not log this failure as an error. This PR introduces a change that causes TuneD to log such failures as debug messages only, along with some refactoring/simplification of the relevant functions.
Resolves: RHEL-46560

plugin_scheduler: Adjust error logging in _set_affinity

---

tuned/units/manager.py

Not clearing it before a profile switch would
result in never deleting the original plugin
objects - those would accumulate in memory with
each profile switch.
TBH, I believe we could get rid of the plugin repository
class altogether, I'm not quite sure what's its responsibility
and why we need it when we have the plugin manager.

Clear plugin repository when stopping tuning

---

tuned/ppd/controller.py

Since 6ef5b58e , switch_profile expects self._on_battery to be set, but when it's called in Controller.initialize, it is called before we do self._on_battery = False , and will crash with
AttributeError: 'Controller' object has no attribute '_on_battery' if the requested profile is not the currently active one.
This fixes that by moving the call to switch_profile after self._on_battery is set.

controller init: set _on_battery before switching profile

---

Makefile
tests/beakerlib/Traceback-caused-by-scheduler-plugin-with/runtest.sh
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/runtest.sh
tests/beakerlib/bz2071418-TuneD-exits-on-duplicate-config-lines-new/runtest.sh
tests/beakerlib/error-messages/runtest.sh
tests/beakerlib/variables-support-in-profiles/runtest.sh
tuned.spec
tuned/consts.py
tuned/gtk/gui_profile_loader.py

- improved conditionals for better readability
- fixed tuned-ppd not to run install twice
- used macro for profiles path

spec: used macro for profiles path and other fixes

---

Makefile
tuned.spec
tuned/consts.py
tuned/ppd/config.py
tuned/ppd/controller.py

This PR brings another round of tuned-ppd adjustments and bug fixes. The individual commit messages explain why the changes are being made.
The most prominent change is dropping reverse profile mapping, i.e., from TuneD to PPD profiles. Instead, the daemon now keeps track of the currently active profile and the so-called base profile. This improves tuned-ppd in two ways:
1. Profile mappings now don't have to be injective.
2. When tuned-ppd is restarted, the initial profile is not the last active profile as inferred from the restored TuneD profile, but the last base profile, as saved into a file by tuned-ppd. The active and the base profile may differ due to profile holds being active before the restart. These should arguably be released when tuned-ppd is restarted.

More tuned-ppd adjustments

---

tuned/plugins/plugin_cpu.py

The no_turbo knob only recognizes 0 or 1, so we have to convert the option value defined in the profile to an integer if necessary.
Related: #630
Resolves: RHEL-51760

Parse no_turbo cpu plugin option using commands.get_bool

---

functions

cpuspeed has not been in Fedora since 2011 [1] and last time in RHEL 6.
it should be fairly safe to drop support for it now
[1] https://bugzilla.redhat.com/show_bug.cgi?id=713572

drop support for cpuspeed

---

tuned/plugins/plugin_service.py

Systemd reads all conf files from a service drop-in directory and merges them.
This change enables the following use case:
Tuning unrelated but local changes can be put into - say:
/etc/systemd/system/sfptpd.service.d/local.conf
while a simple tuning such as the process affinity mask is rolled out via a tuned profile, like this:
`tuned.conf` snippet:
```
[service]
service.sfptpd=,file:${i:PROFILE_DIR}/tuned-sfptpd.conf
```
`tuned-sfptpd.conf`:
```
[Service]
CPUAffinity=32
```
---
Arguably, this is a natural change, i.e. it establishes symmetry in `cfg_install()` to `cfg_uninstall()`, because `cfg_uninstall()` already allows for the service drop-in directory not being empty.

Allow shared service drop-in directory

---

tuned-adm.py

When the value passed to `--timeout` is 0, the `check_positive` function will check the passed value and still prompt that the passed value needs to be greater than or equal to 0. As shown below：
```bash
ubuntu@VM-24-14-ubuntu:~/github/tuned$ tuned-adm --timeout 0
usage: tuned-adm [-h] [--version] [--debug] [--async] [--timeout TIMEOUT] [--loglevel LOGLEVEL] {list,active,off,profile,profile_info,recommend,verify,auto_profile,profile_mode} ...
tuned-adm: error: argument --timeout/-t: 0 has to be >= 0
```
You can also change `if <= 0` to `if < 0`, but I am not sure whether the `--timeout` value can be 0, so I changed the error message instead of `if <= 0`.

`check_positive` has some contradictions

---

tuned/plugins/base.py

Need to expand variables before calling the `@command` function. This is actually done for `_execute_all[_non]_device_commands` and `_verify_all_non_device_commands`, but not in `_verify_all_device_commands`.
This adds the missing expansion.

fix: expand variables in Plugin._verify_all_device_commands

---

tuned/plugins/plugin_scheduler.py

The `perf.evlist.read_on_cpu` function may return instances of classes that do not have the `type` attribute, e.g. `perf.lost_event`. Make sure we do not read the `type` attribute if we are not sure that it exists.

scheduler: Do not assume that perf events have type attribute

---

Makefile
tuned-ppd.py
tuned.spec
tuned/consts.py
tuned/ppd/dbus.conf
tuned/ppd/tuned-ppd.dbus.service
tuned/ppd/tuned-ppd.policy
tuned/ppd/tuned-ppd.service

Since version 0.20, power-profiles-daemon exposes
its DBus interface under "org.freedesktop.UPower.PowerProfiles" alongside the previous name. To be compatible with PPD, this commit implements the same change into tuned-ppd.
Resolves: #683

tuned-ppd: Support the new UPower PPD namespace

---

tuned/ppd/controller.py

To behave the same as power-profiles-daemon, the power-saver profile holds should have priority even if performance holds were added later.

tuned-ppd: Use effective hold profile when adding profile holds

---

tuned/exports/dbus_exporter.py
tuned/exports/dbus_exporter_with_properties.py
tuned/ppd/controller.py
tuned/ppd/tuned-ppd.policy

Rename HoldProfile/ReleaseProfile polkit actions to hold-profile/release-profile.
Add the switch-profile action and check against it when switching the profile using the ActiveProfile DBus property.
The changes require some refactoring of the DBusExporter class, mainly because we need to be able to supply a custom polkit action name instead of deriving it from the DBus method name.

tuned-ppd: Unify polkit policy with power-profiles-daemon

---

tuned.spec

Set an Obsoletes: tag to remove power-profiles-daemon package.
Resolves: #2293628

Obsolete power-profiles-daemon

---

profiles/accelerator-performance/tuned.conf
profiles/latency-performance/tuned.conf
profiles/mssql/tuned.conf
profiles/oracle/tuned.conf
profiles/postgresql/tuned.conf
profiles/sap-hana/tuned.conf
profiles/spectrumscale-ece/tuned.conf
profiles/spindown-disk/tuned.conf
profiles/throughput-performance/tuned.conf
profiles/virtual-guest/tuned.conf
profiles/virtual-host/tuned.conf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/post-vars/tuned.conf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/post/tuned.conf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/post2/tuned.conf
tuned/plugins/plugin_vm.py
tuned/utils/commands.py

The options interact within these two pairs: when `dirty_bytes` is set, `dirty_ratio` is automatically set to 0 and vice versa. Rollback thus does not work out of the box when setting these options via the sysctl plugin.
This PR adds explicit support for the options into the VM plugin: the new custom commands check whether the value set in the profile is permitted and the rollback is adjusted: the option that was not 0 before the profile switch is reverted.
@jmencak, feel free to test this.

Explicitly support vm.dirty_(bytes|ratio) and vm.dirty_background_(bytes|ratio)

---

experiments/powertop2tuned.py

It obeys defaults from the consts.
It could be also improved to obey TuneD main configuration, but it's not a problem at the moment, because the path is configurable in the powertop2tuned. Support of the TuneD main configuration would require changes in the main configuration file, because at the moment we do not explicitly mark there the user profile directory.

powertop2tuned: use default user profile path from the consts

---

tuned/ppd/controller.py

Add a check which raises an error if the caller of ReleaseProfile
is not identical to the caller of HoldProfile.
Do not number cookies from 0, use pseudo-random integers.
Do not allow null cookies, which may cause issues in clients.
E.g., in gnome-settings-daemon, a null cookie means that it
currently has no active hold.

tuned-ppd: Disallow releasing profile holds of other processes

---

tuned/ppd/controller.py

To be compatible with Python 3.9.
Resolves: RHEL-68208

tuned-ppd: Remove the use of StrEnum

---

tuned/plugins/plugin_cpu.py

Besides values specified in `energy_performance_available_preferences`, `energy_performance_preference` also accepts numeric values to allow finer controlling. This PR allows valid numeric values for `energy_performance_preference` in plugin `cpu`.

plugin_cpu: allow raw energy_performance_preference values

---

tuned/plugins/plugin_scheduler.py

sched_wakeup_granularity_ns - removed
sched_min_granularity_ns    - now sched_base_slice_ns, same units and scale
sched_latency_ns            - removed

scheduler: updated sched knobs for kernels 6.6+

---

tuned/plugins/plugin_scheduler.py

Include the current affinity of the process, its cmdline, and its cgroups in the logs. This may help identify issues with tuning, e.g., in cases when the process disappears soon after affining it fails.
Resolves: RHEL-69933
Update: It may happen that a process gets moved into a blacklisted cgroup
after the initial filtering of processes according to the blacklist.
When setting its affinity fails, re-check whether that is the case,
and if yes, ignore the error.
Resolves: RHEL-72981

scheduler: Log process info when its affinity cannot be changed and re-check blacklisted cgroups

---

tuned.spec
tuned/consts.py
tuned/plugins/plugin_scheduler.py

Requested in: https://src.fedoraproject.org/rpms/tuned/pull-request/8

plugin_scheduler: make perf support optional

---

doc/manual/Makefile
doc/manual/modules/performance/con_built-in-functions-in-tuned-profiles.adoc
doc/manual/modules/performance/con_inheritance-between-tuned-profiles.adoc
doc/manual/modules/performance/con_tuned-plug-ins.adoc
doc/manual/modules/performance/con_variables-and-built-in-functions-in-tuned-profiles.adoc
doc/manual/modules/performance/con_variables-in-tuned-profiles.adoc
doc/manual/modules/performance/proc_creating-new-tuned-profiles.adoc
doc/manual/modules/performance/proc_installing-and-enabling-tuned.adoc
doc/manual/modules/performance/proc_listing-available-tuned-profiles.adoc
doc/manual/modules/performance/proc_modifying-existing-tuned-profiles.adoc
doc/manual/modules/performance/proc_setting-a-tuned-profile.adoc
doc/manual/modules/performance/proc_setting-the-disk-scheduler-using-tuned.adoc
doc/manual/modules/performance/ref_tuned-profiles-distributed-with-rhel.adoc
tuned.spec
tuned/plugins/plugin_bootloader.py
tuned/plugins/plugin_net.py
tuned/plugins/plugin_scheduler.py
tuned/plugins/plugin_service.py

With this patch the documentation will be also generated on RHEL with now obsoleted asciidoc tool. The styling is a bit lame, but it's usable.

doc: enable documentation generation on RHEL with asciidoc

---

tuned/ppd/controller.py

Two adjustments needed:
- If multiple profile changes happen too quickly, we must handle the signal only from the last one - i.e., the one that matches the current TuneD profile.
- We must not clear profile holds with each signal from TuneD - the signals come even if the profile change was initiated by tuned-ppd itself.

tuned-ppd: Fix handling of profile change signals from TuneD

---

tests/unit/plugins/test_base.py
tuned/hardware/inventory.py
tuned/monitors/monitor_net.py
tuned/plugins/base.py
tuned/plugins/hotplug.py
tuned/plugins/plugin_acpi.py
tuned/plugins/plugin_audio.py
tuned/plugins/plugin_bootloader.py
tuned/plugins/plugin_cpu.py
tuned/plugins/plugin_disk.py
tuned/plugins/plugin_irq.py
tuned/plugins/plugin_irqbalance.py
tuned/plugins/plugin_mounts.py
tuned/plugins/plugin_net.py
tuned/plugins/plugin_scheduler.py
tuned/plugins/plugin_scsi_host.py
tuned/plugins/plugin_selinux.py
tuned/plugins/plugin_systemd.py
tuned/plugins/plugin_uncore.py
tuned/plugins/plugin_usb.py
tuned/plugins/plugin_video.py
tuned/plugins/plugin_vm.py

This will not completely resolve RHEL-60906, because there will be always race condition if the rename event happens before the instance is fully initialized, but it should significantly improve the situation.
Drawback is that it can report in the logs device names that shouldn't be matched by the plugin_net instance, i.e. it matches devices according to their original names but accesses them with their new names. This can be confusing. Also in the runtime API (e.g. for removal of the device from the instance), the original device names have to be used. For insertion of the device to the instance, new names have to be used. This can be even more confusing.
Unfortunately, there probably isn't better alternative now, because for correct operation we would have to handle rename by removal …

plugin_net: added support for hotplug and rename

---

Makefile
tuned.spec

This is required by Fedora 42 /usr/bin /usr/sbin merge.

makefile: added support for installation to custom $BINDIR/$SBINDIR

---

profiles/balanced/tuned.conf
profiles/powersave/tuned.conf

First, always prefer schedutil for balanced/powersave. On platforms where this governor is available, this enables Energy-Aware-Scheduling which offers the best power efficiency and performance combination. There is absolutely no reason to use another governor by default in the "balanced" profile on these systems, in particular.
Second, swap around "conservative" and "ondemand". "conservative" is supposed to be lower power and higher latency. The commit that made this change [1] tested on a single server platform (10 years ago), but came to the wrong conclusion. Dividing the throughput by power numbers of that commit, "conservative" did in fact provide better performance/watt, which is the intent of lower-power modes. The fact that it also happened to provide better overall performance …

profiles: Correct CPU governor settings

---

tuned/plugins/plugin_net.py

Parsing ethtool output has been broken for several years, since `ethtool -c` started producing a line resembling `CQE mode RX: n/a  TX: n/a`. This prevents setting any [net] coalesce= options, which log `tuned.plugins.plugin_net: unknown coalesce parameter(s): {'CQE mode RX'}`.
Substituting `cqe-mode-rx:` for `CQE mode RX:` resolves the issue, although there is a conflict with the `adaptive-tx` workaround which prevents us from supporting `cqe-mode-tx` directly. Do not attempt to address that issue as part of this change.
Fixes #726.

plugin_net: handle cqe-mode-rx ethtool option

---

tuned/utils/commands.py

Not all platforms can offline CPUs. On those that can't, there is no "online" attribute. Default to online in that case.

utils.commands: Fix CPU online detection when not present

---

00_tuned

Without exporting the grub variables, they are only available in the main grub menu[0]. When descending in a submenu (like in default Debian for example), tuned_* variable are expanded to the empty string and, so, tuned kernel cmdline tuning is effectively disabled.
With the export, variables are available in submenus and tuned tuning is applied as expected.
[0]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1094201#10

bootloader: export Grub variables to make them available in submenus

---

tuned/plugins/plugin_scheduler.py

Split this off #628 to simplify integration.

plugin_scheduler: add switch to disable processing of kthreads

---

Makefile

Similar to #729 I would like to add this minor change to make packaging TuneD a little bit easier on distros that don't use `libexec`.

Makefile: Add support for installation to custom $LIBEXECDIR

---

compile_plugin_docs.py
tuned/daemon/daemon.py
tuned/monitors/repository.py
tuned/plugins/repository.py
tuned/profiles/functions/parser.py
tuned/profiles/functions/repository.py
tuned/profiles/variables.py
tuned/utils/class_loader.py

While fixing this, I got confused by the naming of the `PluginLoader` class. In the first commit, I propose to rename it to `ClassLoader`, and fix one of its methods so that it truly behaves like an abstract class.
For the race fix itself, see the second commit.
Resolves: RHEL-75773

Fix races occuring when two threads expand variables at the same time

---

tuned-main.conf
tuned/consts.py
tuned/daemon/controller.py
tuned/utils/global_config.py

Timeout in seconds to maximally wait until udev settles. If set to value bigger than 0, it will either wait until udev settles or the timeout occurs. Disable with 0.
Resolves: RHEL-88238

tuned-main.conf: added startup_udev_settle_wait option

---

tests/beakerlib/error-messages/runtest.sh

Library API has been changed downstream and we need to reflect those changes in upstream.

tests/beakerlib: remove old API call.

---

tests/beakerlib/Expose-TuneD-API-to-the-Unix-Domain-Socket/runtest.sh

This PR should fix recent test failures in Fedora Rawhide (for some reason, Rawhide has netcat installed by default).

beakerlib: Use ncat explicitly instead of nc

---

functions

Without the redirect to /dev/null, an error message would be reported in TuneD logs on aarch64 machines, which do not have the kernel module.
Resolves: RHEL-79943

functions: Silence errors if module kvm_intel does not exist

---

doc/manual/modules/performance/con_inheritance-between-tuned-profiles.adoc
doc/manual/modules/performance/proc_creating-new-tuned-profiles.adoc
profiles/balanced/tuned.conf
profiles/powersave/tuned.conf
profiles/server-powersave/tuned.conf
profiles/spindown-disk/tuned.conf
tuned/plugins/plugin_scsi_host.py

Using `min_power` can lead to data loss, and `med_power_with_dipm`
delivers similar power savings without the chance of data loss. [1]
`med_power_with_dipm` is the default setting[2] in upstream Linux for
SATA Link Power Management, and should provide significant power
savings on laptops using SATA drives over `medium_power`.
[1] https://hansdegoede.livejournal.com/18412.html
[2] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/ata/Kconfig?id=5433f0e7427ae4f5b128d89ec16ccaafc9fef5ee
**Note:** Testing on a SATA system would be appreciated to confirm this patch is setting `med_power_with_dipm` as expected, since unfortunately I'm not sure when I'll be able to get back to my desktop at home

profiles: use `med_power_with_dipm` for SATA ALPM

---

profiles/network-latency/tuned.conf

`rcutree.nohz_full_patience_delay` is a new kernel parameter added in 6.11. For more details, see https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=68d124b0999919015e6d23008eafea106ec6bb40.

network_latency: Set non-zero rcutree.nohz_full_patience_delay

---

tuned/profiles/functions/function_calc_isolated_cores.py

This makes the function output shorter which is desirable with many CPUs when the function is used, e.g., to compute the content of the isolcpus kernel argument.
Resolves: RHEL-75751

functions: Make calc_isolated_cores return CPU ranges

---

tuned/ppd/controller.py

See individual commits for more details.

tuned-ppd: Fix inotify watch for performance degradation

---

tuned/ppd/config.py
tuned/ppd/controller.py
tuned/ppd/ppd.conf

The thinkpad_function_keys feature is incorrectly named, so rename it to sysfs_acpi_monitor to be more correct.
It is also a useful feature - if profiles are updated on Fedora 41 outside of tuned, then they are not reflected in tuned or gnome-settings (or likely KDE, though I didn't test that). Enable the feature by default.
Tested on multiple devices. As a note - I expect this feature to be useful to any vendor supporting platform profiles, not just Thinkpads (though it does mean our function keys work correctly again which is nice)
Thanks
Mark

Fix thinkpad_function_keys feature

---

tuned/plugins/plugin_irqbalance.py
tuned/plugins/plugin_scheduler.py
tuned/utils/commands.py

Now the irqbalance plugin will work even if perf is unavailable. Also improved perf detection in the scheduler plugin. If the perf.cpu_map() fails for some reason, perf is disabled and the perf library will not segfault.

perf: dropped from irqbalance and improved detection in scheduler

---

tuned/consts.py
tuned/profiles/loader.py
tuned/profiles/merger.py
tuned/profiles/profile.py
tuned/profiles/unit.py

When a child profile overwrites an option defined by its parent,
the option stays in its place in the option dictionary. Until now, this
prevented the child profile from using any _new_ variables in the option
definition, because those would get added to the end of the option
dictionary. As a workaround (see, e.g., redhat-performance#239), such variables would have
to be pre-defined (empty) in the parent profile. However, there is no
suitable workaround if we do not want to touch the parent profile.
This commit adds a new `prepend` option available in variable units.
With this option set to true, new variables are prepended before
parent variables instead of being added to the end. The location of
overwritten variables is not changed, i.e., they remain in their place.
As part of this …

variables: Add an option to prepend child variables before parent ones

---

tuned/admin/admin.py
tuned/daemon/daemon.py

This way, the exception gets caught in tuned.py,
which prints an error message and exits with
non-zero error code, providing feedback to
tuned-adm. Previously, tuned-adm would have no
way of knowing that TuneD failed.
Resolves: RHEL-71304

Re-raise daemon init exception in no-daemon mode

---

.packit.yaml

BTW, does it still make sense to build and test the newest upstream for CentOS 7?

CI: build and test for c10s

---

tuned/plugins/plugin_disk.py

Add support for MMC (MultiMediaCard) devices in tuned's disk plugin.
fixes: #776

plugins: Support MMC devices

---

tuned/daemon/controller.py

udev-settle: obey udev buffer size and handle possible tracebacks

---

profiles/accelerator-performance/tuned.conf
profiles/latency-performance/tuned.conf
profiles/mssql/tuned.conf
profiles/oracle/tuned.conf
profiles/sap-hana/tuned.conf
profiles/spectrumscale-ece/tuned.conf
profiles/spindown-disk/tuned.conf
profiles/throughput-performance/tuned.conf
profiles/virtual-guest/tuned.conf
profiles/virtual-host/tuned.conf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/post-vars/tuned.conf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/post/tuned.conf
tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/post2/tuned.conf
tuned/plugins/plugin_vm.py

Same for dirty_background_ratio and dirty_background_bytes.
Using both the ratio and the bytes is not compatible with the current profile inheritance implementation, because it is not possible for dirty_bytes in a child profile to override dirty_ratio in its parent profile.
Resolves: RHEL-101578

vm: Deprecate dirty_ratio in favour of dirty_bytes with %
